// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'make dev' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil)
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"

	"github.com/bmcdonald3/fms/apis/firmware.management.io/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetDeviceProfiles retrieves all deviceprofiles
func (c *Client) GetDeviceProfiles(ctx context.Context) ([]v1.DeviceProfile, error) {
	var response []v1.DeviceProfile
	if err := c.doRequest(ctx, "GET", "/deviceprofiles", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetDeviceProfile retrieves a specific DeviceProfile by UID
func (c *Client) GetDeviceProfile(ctx context.Context, uid string) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	endpoint := fmt.Sprintf("/deviceprofiles/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateDeviceProfile creates a new DeviceProfile
func (c *Client) CreateDeviceProfile(ctx context.Context, req CreateDeviceProfileRequest) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	if err := c.doRequest(ctx, "POST", "/deviceprofiles", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateDeviceProfile updates an existing DeviceProfile
func (c *Client) UpdateDeviceProfile(ctx context.Context, uid string, req UpdateDeviceProfileRequest) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	endpoint := fmt.Sprintf("/deviceprofiles/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchDeviceProfile patches an existing DeviceProfile spec with the specified patch data and content type
func (c *Client) PatchDeviceProfile(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	endpoint := fmt.Sprintf("/deviceprofiles/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateDeviceProfileStatus updates only the status of an existing DeviceProfile
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateDeviceProfileStatus(ctx context.Context, uid string, status v1.DeviceProfileStatus) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	endpoint := fmt.Sprintf("/deviceprofiles/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchDeviceProfileStatus patches only the status of an existing DeviceProfile
// Supports JSON Merge Patch by default. Use PatchDeviceProfileStatusWithType for other patch formats.
func (c *Client) PatchDeviceProfileStatus(ctx context.Context, uid string, patchData []byte) (*v1.DeviceProfile, error) {
	return c.PatchDeviceProfileStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchDeviceProfileStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchDeviceProfileStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.DeviceProfile, error) {
	var result v1.DeviceProfile
	endpoint := fmt.Sprintf("/deviceprofiles/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteDeviceProfile deletes a DeviceProfile by UID
func (c *Client) DeleteDeviceProfile(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/deviceprofiles/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetFirmwareProfiles retrieves all firmwareprofiles
func (c *Client) GetFirmwareProfiles(ctx context.Context) ([]v1.FirmwareProfile, error) {
	var response []v1.FirmwareProfile
	if err := c.doRequest(ctx, "GET", "/firmwareprofiles", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetFirmwareProfile retrieves a specific FirmwareProfile by UID
func (c *Client) GetFirmwareProfile(ctx context.Context, uid string) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	endpoint := fmt.Sprintf("/firmwareprofiles/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateFirmwareProfile creates a new FirmwareProfile
func (c *Client) CreateFirmwareProfile(ctx context.Context, req CreateFirmwareProfileRequest) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	if err := c.doRequest(ctx, "POST", "/firmwareprofiles", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateFirmwareProfile updates an existing FirmwareProfile
func (c *Client) UpdateFirmwareProfile(ctx context.Context, uid string, req UpdateFirmwareProfileRequest) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	endpoint := fmt.Sprintf("/firmwareprofiles/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchFirmwareProfile patches an existing FirmwareProfile spec with the specified patch data and content type
func (c *Client) PatchFirmwareProfile(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	endpoint := fmt.Sprintf("/firmwareprofiles/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateFirmwareProfileStatus updates only the status of an existing FirmwareProfile
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateFirmwareProfileStatus(ctx context.Context, uid string, status v1.FirmwareProfileStatus) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	endpoint := fmt.Sprintf("/firmwareprofiles/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchFirmwareProfileStatus patches only the status of an existing FirmwareProfile
// Supports JSON Merge Patch by default. Use PatchFirmwareProfileStatusWithType for other patch formats.
func (c *Client) PatchFirmwareProfileStatus(ctx context.Context, uid string, patchData []byte) (*v1.FirmwareProfile, error) {
	return c.PatchFirmwareProfileStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchFirmwareProfileStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchFirmwareProfileStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.FirmwareProfile, error) {
	var result v1.FirmwareProfile
	endpoint := fmt.Sprintf("/firmwareprofiles/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteFirmwareProfile deletes a FirmwareProfile by UID
func (c *Client) DeleteFirmwareProfile(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/firmwareprofiles/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetLookupJobs retrieves all lookupjobs
func (c *Client) GetLookupJobs(ctx context.Context) ([]v1.LookupJob, error) {
	var response []v1.LookupJob
	if err := c.doRequest(ctx, "GET", "/lookupjobs", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetLookupJob retrieves a specific LookupJob by UID
func (c *Client) GetLookupJob(ctx context.Context, uid string) (*v1.LookupJob, error) {
	var result v1.LookupJob
	endpoint := fmt.Sprintf("/lookupjobs/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateLookupJob creates a new LookupJob
func (c *Client) CreateLookupJob(ctx context.Context, req CreateLookupJobRequest) (*v1.LookupJob, error) {
	var result v1.LookupJob
	if err := c.doRequest(ctx, "POST", "/lookupjobs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateLookupJob updates an existing LookupJob
func (c *Client) UpdateLookupJob(ctx context.Context, uid string, req UpdateLookupJobRequest) (*v1.LookupJob, error) {
	var result v1.LookupJob
	endpoint := fmt.Sprintf("/lookupjobs/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchLookupJob patches an existing LookupJob spec with the specified patch data and content type
func (c *Client) PatchLookupJob(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.LookupJob, error) {
	var result v1.LookupJob
	endpoint := fmt.Sprintf("/lookupjobs/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateLookupJobStatus updates only the status of an existing LookupJob
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateLookupJobStatus(ctx context.Context, uid string, status v1.LookupJobStatus) (*v1.LookupJob, error) {
	var result v1.LookupJob
	endpoint := fmt.Sprintf("/lookupjobs/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchLookupJobStatus patches only the status of an existing LookupJob
// Supports JSON Merge Patch by default. Use PatchLookupJobStatusWithType for other patch formats.
func (c *Client) PatchLookupJobStatus(ctx context.Context, uid string, patchData []byte) (*v1.LookupJob, error) {
	return c.PatchLookupJobStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchLookupJobStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchLookupJobStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.LookupJob, error) {
	var result v1.LookupJob
	endpoint := fmt.Sprintf("/lookupjobs/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteLookupJob deletes a LookupJob by UID
func (c *Client) DeleteLookupJob(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/lookupjobs/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetUpdateJobs retrieves all updatejobs
func (c *Client) GetUpdateJobs(ctx context.Context) ([]v1.UpdateJob, error) {
	var response []v1.UpdateJob
	if err := c.doRequest(ctx, "GET", "/updatejobs", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetUpdateJob retrieves a specific UpdateJob by UID
func (c *Client) GetUpdateJob(ctx context.Context, uid string) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	endpoint := fmt.Sprintf("/updatejobs/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateUpdateJob creates a new UpdateJob
func (c *Client) CreateUpdateJob(ctx context.Context, req CreateUpdateJobRequest) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	if err := c.doRequest(ctx, "POST", "/updatejobs", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateJob updates an existing UpdateJob
func (c *Client) UpdateUpdateJob(ctx context.Context, uid string, req UpdateUpdateJobRequest) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	endpoint := fmt.Sprintf("/updatejobs/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateJob patches an existing UpdateJob spec with the specified patch data and content type
func (c *Client) PatchUpdateJob(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	endpoint := fmt.Sprintf("/updatejobs/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateJobStatus updates only the status of an existing UpdateJob
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateUpdateJobStatus(ctx context.Context, uid string, status v1.UpdateJobStatus) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	endpoint := fmt.Sprintf("/updatejobs/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateJobStatus patches only the status of an existing UpdateJob
// Supports JSON Merge Patch by default. Use PatchUpdateJobStatusWithType for other patch formats.
func (c *Client) PatchUpdateJobStatus(ctx context.Context, uid string, patchData []byte) (*v1.UpdateJob, error) {
	return c.PatchUpdateJobStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchUpdateJobStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchUpdateJobStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateJob, error) {
	var result v1.UpdateJob
	endpoint := fmt.Sprintf("/updatejobs/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteUpdateJob deletes a UpdateJob by UID
func (c *Client) DeleteUpdateJob(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/updatejobs/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetUpdateProfiles retrieves all updateprofiles
func (c *Client) GetUpdateProfiles(ctx context.Context) ([]v1.UpdateProfile, error) {
	var response []v1.UpdateProfile
	if err := c.doRequest(ctx, "GET", "/updateprofiles", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetUpdateProfile retrieves a specific UpdateProfile by UID
func (c *Client) GetUpdateProfile(ctx context.Context, uid string) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	endpoint := fmt.Sprintf("/updateprofiles/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateUpdateProfile creates a new UpdateProfile
func (c *Client) CreateUpdateProfile(ctx context.Context, req CreateUpdateProfileRequest) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	if err := c.doRequest(ctx, "POST", "/updateprofiles", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateProfile updates an existing UpdateProfile
func (c *Client) UpdateUpdateProfile(ctx context.Context, uid string, req UpdateUpdateProfileRequest) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	endpoint := fmt.Sprintf("/updateprofiles/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateProfile patches an existing UpdateProfile spec with the specified patch data and content type
func (c *Client) PatchUpdateProfile(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	endpoint := fmt.Sprintf("/updateprofiles/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateProfileStatus updates only the status of an existing UpdateProfile
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateUpdateProfileStatus(ctx context.Context, uid string, status v1.UpdateProfileStatus) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	endpoint := fmt.Sprintf("/updateprofiles/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateProfileStatus patches only the status of an existing UpdateProfile
// Supports JSON Merge Patch by default. Use PatchUpdateProfileStatusWithType for other patch formats.
func (c *Client) PatchUpdateProfileStatus(ctx context.Context, uid string, patchData []byte) (*v1.UpdateProfile, error) {
	return c.PatchUpdateProfileStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchUpdateProfileStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchUpdateProfileStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateProfile, error) {
	var result v1.UpdateProfile
	endpoint := fmt.Sprintf("/updateprofiles/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteUpdateProfile deletes a UpdateProfile by UID
func (c *Client) DeleteUpdateProfile(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/updateprofiles/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetUpdateTasks retrieves all updatetasks
func (c *Client) GetUpdateTasks(ctx context.Context) ([]v1.UpdateTask, error) {
	var response []v1.UpdateTask
	if err := c.doRequest(ctx, "GET", "/updatetasks", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetUpdateTask retrieves a specific UpdateTask by UID
func (c *Client) GetUpdateTask(ctx context.Context, uid string) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	endpoint := fmt.Sprintf("/updatetasks/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateUpdateTask creates a new UpdateTask
func (c *Client) CreateUpdateTask(ctx context.Context, req CreateUpdateTaskRequest) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	if err := c.doRequest(ctx, "POST", "/updatetasks", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateTask updates an existing UpdateTask
func (c *Client) UpdateUpdateTask(ctx context.Context, uid string, req UpdateUpdateTaskRequest) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	endpoint := fmt.Sprintf("/updatetasks/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateTask patches an existing UpdateTask spec with the specified patch data and content type
func (c *Client) PatchUpdateTask(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	endpoint := fmt.Sprintf("/updatetasks/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateUpdateTaskStatus updates only the status of an existing UpdateTask
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateUpdateTaskStatus(ctx context.Context, uid string, status v1.UpdateTaskStatus) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	endpoint := fmt.Sprintf("/updatetasks/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchUpdateTaskStatus patches only the status of an existing UpdateTask
// Supports JSON Merge Patch by default. Use PatchUpdateTaskStatusWithType for other patch formats.
func (c *Client) PatchUpdateTaskStatus(ctx context.Context, uid string, patchData []byte) (*v1.UpdateTask, error) {
	return c.PatchUpdateTaskStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchUpdateTaskStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchUpdateTaskStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.UpdateTask, error) {
	var result v1.UpdateTask
	endpoint := fmt.Sprintf("/updatetasks/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteUpdateTask deletes a UpdateTask by UID
func (c *Client) DeleteUpdateTask(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/updatetasks/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
