// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains client-side request/response models.
// Generated from: pkg/codegen/templates/client-models.go.tmpl
//
// To modify client models:
//  1. Edit the template file: pkg/codegen/templates/client-models.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// DEPRECATED: This template is a legacy stub. The actual client models are
// generated in models.go.tmpl and used by both server and client.
//
// Generated request types:
//   - CreateResourceRequest: Create operation with metadata
//   - UpdateResourceRequest: Update operation with partial fields
//   - DeleteResponse: Confirmation of deletion
//
// Note: This file contains TODO comments indicating that resource-specific
// fields should be added. Consider migrating to the unified models.go.tmpl
// approach or implementing spec field embedding.
//
// To implement full spec support:
//  1. Import resource packages
//  2. Embed ResourceSpec in request structs
//  3. Use json:",inline" tag for proper serialization
//
// To add validation:
//  1. Add validate tags (e.g., validate:"required,min=3")
//  2. Use go-playground/validator in client before sending
package client

import (
	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/user/fms/apis/example.fabrica.dev/v1"
)

// CreateDeviceProfileRequest represents a request to create a DeviceProfile
type CreateDeviceProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata" validate:"required"`
	Spec        v1.DeviceProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// UpdateDeviceProfileRequest represents a request to update a DeviceProfile
type UpdateDeviceProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata,omitempty"`
	Spec        v1.DeviceProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// CreateFirmwareProfileRequest represents a request to create a FirmwareProfile
type CreateFirmwareProfileRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" validate:"required"`
	Spec        v1.FirmwareProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// UpdateFirmwareProfileRequest represents a request to update a FirmwareProfile
type UpdateFirmwareProfileRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty"`
	Spec        v1.FirmwareProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// CreateUpdateJobRequest represents a request to create a UpdateJob
type CreateUpdateJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.UpdateJobSpec  `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// UpdateUpdateJobRequest represents a request to update a UpdateJob
type UpdateUpdateJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.UpdateJobSpec  `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// CreateUpdateProfileRequest represents a request to create a UpdateProfile
type CreateUpdateProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata" validate:"required"`
	Spec        v1.UpdateProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// UpdateUpdateProfileRequest represents a request to update a UpdateProfile
type UpdateUpdateProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata,omitempty"`
	Spec        v1.UpdateProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}
