// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/bmcdonald3/firmware-management-service/fms/apis/firmware.management.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.DeviceProfile{}); err != nil {
		return fmt.Errorf("failed to register DeviceProfile: %w", err)
	}
	if err := gen.RegisterResource(&v1.FirmwareManifest{}); err != nil {
		return fmt.Errorf("failed to register FirmwareManifest: %w", err)
	}
	if err := gen.RegisterResource(&v1.LookupJob{}); err != nil {
		return fmt.Errorf("failed to register LookupJob: %w", err)
	}
	if err := gen.RegisterResource(&v1.UpdateJob{}); err != nil {
		return fmt.Errorf("failed to register UpdateJob: %w", err)
	}
	if err := gen.RegisterResource(&v1.UpdateProfile{}); err != nil {
		return fmt.Errorf("failed to register UpdateProfile: %w", err)
	}

	return nil
}
