// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-20T13:20:44-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for DeviceProfile resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /deviceprofiles (list all deviceprofiles)
//   - GET /deviceprofiles/{uid} (get specific DeviceProfile)
//   - POST /deviceprofiles (create new DeviceProfile)
//   - PUT /deviceprofiles/{uid} (update DeviceProfile spec)
//   - PATCH /deviceprofiles/{uid} (patch DeviceProfile spec)
//   - DELETE /deviceprofiles/{uid} (delete DeviceProfile)
//   - PUT /deviceprofiles/{uid}/status (update DeviceProfile status)
//   - PATCH /deviceprofiles/{uid}/status (patch DeviceProfile status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadDeviceProfile*/SaveDeviceProfile*/DeleteDeviceProfile*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadDeviceProfileWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/fms/apis/example.fabrica.dev/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/fms/internal/storage"
)

// GetDeviceProfiles returns all DeviceProfile resources
func GetDeviceProfiles(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	deviceprofiles, err := storage.LoadAllDeviceProfiles(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load deviceprofiles: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, deviceprofiles)
}

// GetDeviceProfile returns a specific DeviceProfile resource by UID
func GetDeviceProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadDeviceProfile() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	deviceProfile, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, deviceProfile)
}

// CreateDeviceProfile creates a new DeviceProfile resource
func CreateDeviceProfile(w http.ResponseWriter, r *http.Request) {
	var req CreateDeviceProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("DeviceProfile")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	deviceProfile := &v1.DeviceProfile{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "DeviceProfile",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	deviceProfile.Metadata = req.Metadata
	deviceProfile.Metadata.UID = uid
	now := time.Now()
	deviceProfile.Metadata.CreatedAt = now
	deviceProfile.Metadata.UpdatedAt = now

	// Set labels and annotations
	if deviceProfile.Metadata.Labels == nil {
		deviceProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		deviceProfile.Metadata.Labels[k] = v
	}
	if deviceProfile.Metadata.Annotations == nil {
		deviceProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		deviceProfile.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), deviceProfile); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveDeviceProfile(r.Context(), deviceProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save DeviceProfile: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "DeviceProfile", deviceProfile.Metadata.UID, deviceProfile.Metadata.Name, deviceProfile); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for DeviceProfile %s: %v\n", deviceProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, deviceProfile)
}

// UpdateDeviceProfile updates the spec of an existing DeviceProfile resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //deviceprofiles/{uid}/status to update status.
func UpdateDeviceProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	deviceProfile, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}

	var req UpdateDeviceProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		deviceProfile.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	deviceProfile.Spec = req.AsSpec()

	// Update labels and annotations
	if deviceProfile.Metadata.Labels == nil {
		deviceProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		deviceProfile.Metadata.Labels[k] = v
	}
	if deviceProfile.Metadata.Annotations == nil {
		deviceProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		deviceProfile.Metadata.Annotations[k] = v
	}

	// Update timestamp
	deviceProfile.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveDeviceProfile(r.Context(), deviceProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save DeviceProfile: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": deviceProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "DeviceProfile", deviceProfile.Metadata.UID, deviceProfile.Metadata.Name, deviceProfile, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for DeviceProfile %s: %v\n", deviceProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, deviceProfile)
}

// PatchDeviceProfile patches an existing DeviceProfile resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchDeviceProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	deviceProfile, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(deviceProfile.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &deviceProfile.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	deviceProfile.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveDeviceProfile(r.Context(), deviceProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched DeviceProfile: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": deviceProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "DeviceProfile", deviceProfile.Metadata.UID, deviceProfile.Metadata.Name, deviceProfile, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for DeviceProfile %s: %v\n", deviceProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, deviceProfile)
}

// UpdateDeviceProfileStatus updates only the status of a DeviceProfile resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateDeviceProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}

	var statusUpdate v1.DeviceProfileStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveDeviceProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save DeviceProfile status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "DeviceProfile", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for DeviceProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchDeviceProfileStatus patches only the status of a DeviceProfile resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchDeviceProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveDeviceProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched DeviceProfile status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "DeviceProfile", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for DeviceProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteDeviceProfile deletes a DeviceProfile resource
func DeleteDeviceProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("DeviceProfile UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	deviceProfile, err := storage.LoadDeviceProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("DeviceProfile not found: %w", err))
		return
	}

	if err := storage.DeleteDeviceProfile(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete DeviceProfile: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "DeviceProfile", deviceProfile.Metadata.UID, deviceProfile.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for DeviceProfile %s: %v\n", deviceProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "DeviceProfile deleted successfully",
		UID:     uid,
	})
}
