// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-15T15:29:17-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for FirmwareManifest resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /firmwaremanifests (list all firmwaremanifests)
//   - GET /firmwaremanifests/{uid} (get specific FirmwareManifest)
//   - POST /firmwaremanifests (create new FirmwareManifest)
//   - PUT /firmwaremanifests/{uid} (update FirmwareManifest spec)
//   - PATCH /firmwaremanifests/{uid} (patch FirmwareManifest spec)
//   - DELETE /firmwaremanifests/{uid} (delete FirmwareManifest)
//   - PUT /firmwaremanifests/{uid}/status (update FirmwareManifest status)
//   - PATCH /firmwaremanifests/{uid}/status (patch FirmwareManifest status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadFirmwareManifest*/SaveFirmwareManifest*/DeleteFirmwareManifest*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadFirmwareManifestWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/firmware-management-service/fms/apis/firmware.management.io/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/firmware-management-service/fms/internal/storage"
)

// GetFirmwareManifests returns all FirmwareManifest resources
func GetFirmwareManifests(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwaremanifests, err := storage.LoadAllFirmwareManifests(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load firmwaremanifests: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwaremanifests)
}

// GetFirmwareManifest returns a specific FirmwareManifest resource by UID
func GetFirmwareManifest(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadFirmwareManifest() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareManifest, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareManifest)
}

// CreateFirmwareManifest creates a new FirmwareManifest resource
func CreateFirmwareManifest(w http.ResponseWriter, r *http.Request) {
	var req CreateFirmwareManifestRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("FirmwareManifest")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	firmwareManifest := &v1.FirmwareManifest{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "FirmwareManifest",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	firmwareManifest.Metadata = req.Metadata
	firmwareManifest.Metadata.UID = uid
	now := time.Now()
	firmwareManifest.Metadata.CreatedAt = now
	firmwareManifest.Metadata.UpdatedAt = now

	// Set labels and annotations
	if firmwareManifest.Metadata.Labels == nil {
		firmwareManifest.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareManifest.Metadata.Labels[k] = v
	}
	if firmwareManifest.Metadata.Annotations == nil {
		firmwareManifest.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareManifest.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareManifest); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveFirmwareManifest(r.Context(), firmwareManifest); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareManifest: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "FirmwareManifest", firmwareManifest.Metadata.UID, firmwareManifest.Metadata.Name, firmwareManifest); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for FirmwareManifest %s: %v\n", firmwareManifest.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, firmwareManifest)
}

// UpdateFirmwareManifest updates the spec of an existing FirmwareManifest resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //firmwaremanifests/{uid}/status to update status.
func UpdateFirmwareManifest(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	firmwareManifest, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}

	var req UpdateFirmwareManifestRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		firmwareManifest.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	firmwareManifest.Spec = req.AsSpec()

	// Update labels and annotations
	if firmwareManifest.Metadata.Labels == nil {
		firmwareManifest.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareManifest.Metadata.Labels[k] = v
	}
	if firmwareManifest.Metadata.Annotations == nil {
		firmwareManifest.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareManifest.Metadata.Annotations[k] = v
	}

	// Update timestamp
	firmwareManifest.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareManifest(r.Context(), firmwareManifest); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareManifest: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": firmwareManifest.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareManifest", firmwareManifest.Metadata.UID, firmwareManifest.Metadata.Name, firmwareManifest, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for FirmwareManifest %s: %v\n", firmwareManifest.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareManifest)
}

// PatchFirmwareManifest patches an existing FirmwareManifest resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchFirmwareManifest(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	firmwareManifest, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(firmwareManifest.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &firmwareManifest.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	firmwareManifest.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveFirmwareManifest(r.Context(), firmwareManifest); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareManifest: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": firmwareManifest.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareManifest", firmwareManifest.Metadata.UID, firmwareManifest.Metadata.Name, firmwareManifest, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for FirmwareManifest %s: %v\n", firmwareManifest.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareManifest)
}

// UpdateFirmwareManifestStatus updates only the status of a FirmwareManifest resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateFirmwareManifestStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}

	var statusUpdate v1.FirmwareManifestStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareManifest(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareManifest status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareManifest", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for FirmwareManifest %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchFirmwareManifestStatus patches only the status of a FirmwareManifest resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchFirmwareManifestStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareManifest(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareManifest status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareManifest", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for FirmwareManifest %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteFirmwareManifest deletes a FirmwareManifest resource
func DeleteFirmwareManifest(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareManifest UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	firmwareManifest, err := storage.LoadFirmwareManifest(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareManifest not found: %w", err))
		return
	}

	if err := storage.DeleteFirmwareManifest(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete FirmwareManifest: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "FirmwareManifest", firmwareManifest.Metadata.UID, firmwareManifest.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for FirmwareManifest %s: %v\n", firmwareManifest.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "FirmwareManifest deleted successfully",
		UID:     uid,
	})
}
