// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-16T16:21:58-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for FirmwareProfile resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /firmwareprofiles (list all firmwareprofiles)
//   - GET /firmwareprofiles/{uid} (get specific FirmwareProfile)
//   - POST /firmwareprofiles (create new FirmwareProfile)
//   - PUT /firmwareprofiles/{uid} (update FirmwareProfile spec)
//   - PATCH /firmwareprofiles/{uid} (patch FirmwareProfile spec)
//   - DELETE /firmwareprofiles/{uid} (delete FirmwareProfile)
//   - PUT /firmwareprofiles/{uid}/status (update FirmwareProfile status)
//   - PATCH /firmwareprofiles/{uid}/status (patch FirmwareProfile status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadFirmwareProfile*/SaveFirmwareProfile*/DeleteFirmwareProfile*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadFirmwareProfileWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/fms/apis/firmware.management.io/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/fms/internal/storage"
)

// GetFirmwareProfiles returns all FirmwareProfile resources
func GetFirmwareProfiles(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareprofiles, err := storage.LoadAllFirmwareProfiles(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load firmwareprofiles: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareprofiles)
}

// GetFirmwareProfile returns a specific FirmwareProfile resource by UID
func GetFirmwareProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadFirmwareProfile() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareProfile, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareProfile)
}

// CreateFirmwareProfile creates a new FirmwareProfile resource
func CreateFirmwareProfile(w http.ResponseWriter, r *http.Request) {
	var req CreateFirmwareProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("FirmwareProfile")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	firmwareProfile := &v1.FirmwareProfile{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "FirmwareProfile",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	firmwareProfile.Metadata = req.Metadata
	firmwareProfile.Metadata.UID = uid
	now := time.Now()
	firmwareProfile.Metadata.CreatedAt = now
	firmwareProfile.Metadata.UpdatedAt = now

	// Set labels and annotations
	if firmwareProfile.Metadata.Labels == nil {
		firmwareProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareProfile.Metadata.Labels[k] = v
	}
	if firmwareProfile.Metadata.Annotations == nil {
		firmwareProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareProfile.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareProfile); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveFirmwareProfile(r.Context(), firmwareProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareProfile: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "FirmwareProfile", firmwareProfile.Metadata.UID, firmwareProfile.Metadata.Name, firmwareProfile); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for FirmwareProfile %s: %v\n", firmwareProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, firmwareProfile)
}

// UpdateFirmwareProfile updates the spec of an existing FirmwareProfile resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //firmwareprofiles/{uid}/status to update status.
func UpdateFirmwareProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	firmwareProfile, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}

	var req UpdateFirmwareProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		firmwareProfile.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	firmwareProfile.Spec = req.AsSpec()

	// Update labels and annotations
	if firmwareProfile.Metadata.Labels == nil {
		firmwareProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareProfile.Metadata.Labels[k] = v
	}
	if firmwareProfile.Metadata.Annotations == nil {
		firmwareProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareProfile.Metadata.Annotations[k] = v
	}

	// Update timestamp
	firmwareProfile.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareProfile(r.Context(), firmwareProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareProfile: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": firmwareProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareProfile", firmwareProfile.Metadata.UID, firmwareProfile.Metadata.Name, firmwareProfile, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for FirmwareProfile %s: %v\n", firmwareProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareProfile)
}

// PatchFirmwareProfile patches an existing FirmwareProfile resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchFirmwareProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	firmwareProfile, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(firmwareProfile.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &firmwareProfile.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	firmwareProfile.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveFirmwareProfile(r.Context(), firmwareProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareProfile: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": firmwareProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareProfile", firmwareProfile.Metadata.UID, firmwareProfile.Metadata.Name, firmwareProfile, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for FirmwareProfile %s: %v\n", firmwareProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareProfile)
}

// UpdateFirmwareProfileStatus updates only the status of a FirmwareProfile resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateFirmwareProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}

	var statusUpdate v1.FirmwareProfileStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareProfile status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareProfile", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for FirmwareProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchFirmwareProfileStatus patches only the status of a FirmwareProfile resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchFirmwareProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareProfile status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareProfile", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for FirmwareProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteFirmwareProfile deletes a FirmwareProfile resource
func DeleteFirmwareProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareProfile UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	firmwareProfile, err := storage.LoadFirmwareProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareProfile not found: %w", err))
		return
	}

	if err := storage.DeleteFirmwareProfile(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete FirmwareProfile: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "FirmwareProfile", firmwareProfile.Metadata.UID, firmwareProfile.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for FirmwareProfile %s: %v\n", firmwareProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "FirmwareProfile deleted successfully",
		UID:     uid,
	})
}
