// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-16T16:21:58-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for LookupJob resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /lookupjobs (list all lookupjobs)
//   - GET /lookupjobs/{uid} (get specific LookupJob)
//   - POST /lookupjobs (create new LookupJob)
//   - PUT /lookupjobs/{uid} (update LookupJob spec)
//   - PATCH /lookupjobs/{uid} (patch LookupJob spec)
//   - DELETE /lookupjobs/{uid} (delete LookupJob)
//   - PUT /lookupjobs/{uid}/status (update LookupJob status)
//   - PATCH /lookupjobs/{uid}/status (patch LookupJob status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadLookupJob*/SaveLookupJob*/DeleteLookupJob*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadLookupJobWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/fms/apis/firmware.management.io/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/fms/internal/storage"
)

// GetLookupJobs returns all LookupJob resources
func GetLookupJobs(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	lookupjobs, err := storage.LoadAllLookupJobs(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load lookupjobs: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, lookupjobs)
}

// GetLookupJob returns a specific LookupJob resource by UID
func GetLookupJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadLookupJob() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	lookupJob, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, lookupJob)
}

// CreateLookupJob creates a new LookupJob resource
func CreateLookupJob(w http.ResponseWriter, r *http.Request) {
	var req CreateLookupJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("LookupJob")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	lookupJob := &v1.LookupJob{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "LookupJob",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	lookupJob.Metadata = req.Metadata
	lookupJob.Metadata.UID = uid
	now := time.Now()
	lookupJob.Metadata.CreatedAt = now
	lookupJob.Metadata.UpdatedAt = now

	// Set labels and annotations
	if lookupJob.Metadata.Labels == nil {
		lookupJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		lookupJob.Metadata.Labels[k] = v
	}
	if lookupJob.Metadata.Annotations == nil {
		lookupJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		lookupJob.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), lookupJob); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveLookupJob(r.Context(), lookupJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save LookupJob: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "LookupJob", lookupJob.Metadata.UID, lookupJob.Metadata.Name, lookupJob); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for LookupJob %s: %v\n", lookupJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, lookupJob)
}

// UpdateLookupJob updates the spec of an existing LookupJob resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //lookupjobs/{uid}/status to update status.
func UpdateLookupJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	lookupJob, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}

	var req UpdateLookupJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		lookupJob.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	lookupJob.Spec = req.AsSpec()

	// Update labels and annotations
	if lookupJob.Metadata.Labels == nil {
		lookupJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		lookupJob.Metadata.Labels[k] = v
	}
	if lookupJob.Metadata.Annotations == nil {
		lookupJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		lookupJob.Metadata.Annotations[k] = v
	}

	// Update timestamp
	lookupJob.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveLookupJob(r.Context(), lookupJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save LookupJob: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": lookupJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "LookupJob", lookupJob.Metadata.UID, lookupJob.Metadata.Name, lookupJob, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for LookupJob %s: %v\n", lookupJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, lookupJob)
}

// PatchLookupJob patches an existing LookupJob resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchLookupJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	lookupJob, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(lookupJob.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &lookupJob.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	lookupJob.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveLookupJob(r.Context(), lookupJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched LookupJob: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": lookupJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "LookupJob", lookupJob.Metadata.UID, lookupJob.Metadata.Name, lookupJob, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for LookupJob %s: %v\n", lookupJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, lookupJob)
}

// UpdateLookupJobStatus updates only the status of a LookupJob resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateLookupJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}

	var statusUpdate v1.LookupJobStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveLookupJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save LookupJob status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "LookupJob", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for LookupJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchLookupJobStatus patches only the status of a LookupJob resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchLookupJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveLookupJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched LookupJob status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "LookupJob", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for LookupJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteLookupJob deletes a LookupJob resource
func DeleteLookupJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("LookupJob UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	lookupJob, err := storage.LoadLookupJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("LookupJob not found: %w", err))
		return
	}

	if err := storage.DeleteLookupJob(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete LookupJob: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "LookupJob", lookupJob.Metadata.UID, lookupJob.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for LookupJob %s: %v\n", lookupJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "LookupJob deleted successfully",
		UID:     uid,
	})
}
