
// Code generated by Fabrica dev. DO NOT EDIT.
// Template: init/main.go.tmpl
// Generated: 2026-04-16T16:20:24-07:00
//
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	_ "github.com/bmcdonald3/fms/pkg/apiversion"
	"github.com/openchami/fabrica/pkg/versioning"

	

	

	 "github.com/bmcdonald3/fms/internal/storage"
	
	

	 "github.com/bmcdonald3/fms/internal/storage/ent"
	 "github.com/bmcdonald3/fms/internal/storage/ent/migrate"

	
	_ "github.com/mattn/go-sqlite3"
	
	

	

	
"github.com/openchami/fabrica/pkg/events"
"github.com/openchami/fabrica/pkg/reconcile"
"github.com/bmcdonald3/fms/pkg/reconcilers"
	
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	
	// Storage Configuration
	
	DatabaseURL string `mapstructure:"database-url"`
	
	

	

	
	// Reconciliation Configuration
	ReconcileEnabled bool `mapstructure:"reconcile_enabled"`
	ReconcileWorkers int  `mapstructure:"reconcile_workers"`
	

	// Feature Flags
	
	Debug bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         8080,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,
		
		
		DatabaseURL:  "file:./data.db?cache=shared&_fk=1",
		
		
		
		
		ReconcileEnabled: true,
		ReconcileWorkers: 5,
		
		
		Debug: false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "fms",
	Short: "Firmware Management Service",
	Long:  `fms - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the fms server",
	Long:  `Start the fms HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.fms.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	
	
	serveCmd.Flags().String("database-url", "", "Database connection URL")
	
	

	

	

	// Bind flags to viper
	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())

// Add subcommands
rootCmd.AddCommand(serveCmd)
rootCmd.AddCommand(initDBCmd)
rootCmd.AddCommand(versionCmd)
	
	// Generated by Fabrica v0.4.0+: export and import commands (Ent storage only)
	
	rootCmd.AddCommand(newExportCommand())
	rootCmd.AddCommand(newImportCommand())
	
}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".fms")
	}

	// Environment variables
	viper.SetEnvPrefix("FMS")
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting fms server...")

	
	// Initialize storage backend
	
	// Connect to database
	client, err := ent.Open("sqlite3", config.DatabaseURL)
	if err != nil {
		return fmt.Errorf("failed opening connection to sqlite3: %w", err)
	}
	defer client.Close()

	// Run auto-migration
	ctx := context.Background()
	if err := client.Schema.Create(
		ctx,
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
	); err != nil {
		return fmt.Errorf("failed creating schema resources: %w", err)
	}
	log.Println("Database schema migrated successfully")

	// Set Ent client for storage operations
	storage.SetEntClient(client)
	log.Printf("Ent storage initialized with sqlite3 database")
	
	

	

	
// Initialize reconciliation controller with in-memory event bus.
// Events are handled locally; no external broker is required for local dev.
eventBus := events.NewInMemoryEventBus(256, 4)
controller := reconcile.NewController(eventBus, storage.Backend)
reconcileClient := storage.NewStorageClient()
if err := reconcilers.RegisterReconcilers(controller, reconcileClient, eventBus); err != nil {
return fmt.Errorf("failed to register reconcilers: %w", err)
}
go controller.Start(ctx)
log.Printf("Reconciliation controller started with %d workers", config.ReconcileWorkers)
	
	

	// Register resource prefixes for UID generation
	// This is required before any handlers can create resources
	if err := registerResourcePrefixes(); err != nil {
		return fmt.Errorf("failed to register resource prefixes: %w", err)
	}

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	// Version negotiation (Accept header `version=` or URL strategy)
	// Initialize and use global version registry when versioning is enabled.
	// Note: VersionNegotiationMiddleware currently uses versioning.VersionRegistry
	// Versioning support will be fully wired in a future update.
	r.Use(versioning.VersionNegotiationMiddleware(versioning.GlobalVersionRegistry, nil))

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	

// Register routes - generated by 'fabrica generate'
RegisterGeneratedRoutes(r)
r.Get("/health", healthHandler)

// Register custom library routes (not generated — injected per plan guardrail)
RegisterLibraryRoutes(r)

	

	// Create HTTP server
	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		log.Printf("Server starting on %s", addr)
		
		
		log.Printf("Storage: sqlite3 database")
		
		
		

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Server shutting down...")

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"healthy","service":"fms"}`))
}

// registerResourcePrefixes is defined in routes_generated.go




var initDBCmd = &cobra.Command{
Use:   "init-db",
Short: "Initialize the database schema",
Long:  `Connect to the configured database and run schema migrations`,
RunE: func(cmd *cobra.Command, args []string) error {
// Use the config value; DefaultConfig is applied by cobra.OnInitialize.
// Fall back to the default DSN if config was not populated to ensure _fk=1 is present.
dsn := config.DatabaseURL
if dsn == "" {
dsn = "file:./data.db?cache=shared&_fk=1"
}
client, err := ent.Open("sqlite3", dsn)
if err != nil {
return fmt.Errorf("failed opening connection to sqlite3: %w", err)
}
defer client.Close()
ctx := context.Background()
if err := client.Schema.Create(ctx, migrate.WithDropIndex(true), migrate.WithDropColumn(true)); err != nil {
return fmt.Errorf("failed creating schema resources: %w", err)
}
log.Println("Database schema initialized successfully")
return nil
},
}

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Long:  `Print the version number of fms`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("fms v1.0.0")
	},
}

