// Code generated by Fabrica dev. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains request/response models for REST API operations.
// Generated from: pkg/codegen/templates/models.go.tmpl
//
// To modify request/response models:
//  1. Edit the template file: pkg/codegen/templates/models.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated models for each resource:
//   - ResourceResponse: Single resource response (alias to resource type)
//   - ResourcesResponse: List of resources with pagination info
//   - CreateResourceRequest: Create operation request body
//   - UpdateResourceRequest: Update operation request body
//   - DeleteResponse: Delete operation response
//
// Request structure:
//   - Embeds resource Spec fields inline (json:",inline")
//   - Includes metadata fields (Name, Labels, Annotations)
//   - Uses validation tags for required fields
//
// To add custom validation:
//  1. Add validation tags to template (e.g., validate:"required,email")
//  2. Implement validation middleware in handlers
//
// To add additional fields:
//  1. Modify Create/Update request structs in template
//  2. Update corresponding handlers to process new fields
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/bmcdonald3/fms/apis/example.fabrica.dev/v1"
)

// DeviceProfileResponse represents the response for DeviceProfile operations
type DeviceProfileResponse = v1.DeviceProfile

// CreateDeviceProfileRequest represents a request to create a DeviceProfile
type CreateDeviceProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata" validate:"required"`
	Spec        v1.DeviceProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateDeviceProfileRequest) AsSpec() v1.DeviceProfileSpec {
	return r.Spec
}

// UpdateDeviceProfileRequest represents a request to update a DeviceProfile
type UpdateDeviceProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata,omitempty"`
	Spec        v1.DeviceProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateDeviceProfileRequest) AsSpec() v1.DeviceProfileSpec {
	return r.Spec
}

// FirmwareProfileResponse represents the response for FirmwareProfile operations
type FirmwareProfileResponse = v1.FirmwareProfile

// CreateFirmwareProfileRequest represents a request to create a FirmwareProfile
type CreateFirmwareProfileRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" validate:"required"`
	Spec        v1.FirmwareProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateFirmwareProfileRequest) AsSpec() v1.FirmwareProfileSpec {
	return r.Spec
}

// UpdateFirmwareProfileRequest represents a request to update a FirmwareProfile
type UpdateFirmwareProfileRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty"`
	Spec        v1.FirmwareProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateFirmwareProfileRequest) AsSpec() v1.FirmwareProfileSpec {
	return r.Spec
}

// LookupJobResponse represents the response for LookupJob operations
type LookupJobResponse = v1.LookupJob

// CreateLookupJobRequest represents a request to create a LookupJob
type CreateLookupJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.LookupJobSpec  `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateLookupJobRequest) AsSpec() v1.LookupJobSpec {
	return r.Spec
}

// UpdateLookupJobRequest represents a request to update a LookupJob
type UpdateLookupJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.LookupJobSpec  `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateLookupJobRequest) AsSpec() v1.LookupJobSpec {
	return r.Spec
}

// UpdateJobResponse represents the response for UpdateJob operations
type UpdateJobResponse = v1.UpdateJob

// CreateUpdateJobRequest represents a request to create a UpdateJob
type CreateUpdateJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.UpdateJobSpec  `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateUpdateJobRequest) AsSpec() v1.UpdateJobSpec {
	return r.Spec
}

// UpdateUpdateJobRequest represents a request to update a UpdateJob
type UpdateUpdateJobRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.UpdateJobSpec  `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateUpdateJobRequest) AsSpec() v1.UpdateJobSpec {
	return r.Spec
}

// UpdateProfileResponse represents the response for UpdateProfile operations
type UpdateProfileResponse = v1.UpdateProfile

// CreateUpdateProfileRequest represents a request to create a UpdateProfile
type CreateUpdateProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata" validate:"required"`
	Spec        v1.UpdateProfileSpec `json:"spec" validate:"required"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateUpdateProfileRequest) AsSpec() v1.UpdateProfileSpec {
	return r.Spec
}

// UpdateUpdateProfileRequest represents a request to update a UpdateProfile
type UpdateUpdateProfileRequest struct {
	Metadata    fabrica.Metadata     `json:"metadata,omitempty"`
	Spec        v1.UpdateProfileSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string    `json:"labels,omitempty"`
	Annotations map[string]string    `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateUpdateProfileRequest) AsSpec() v1.UpdateProfileSpec {
	return r.Spec
}

// UpdateTaskResponse represents the response for UpdateTask operations
type UpdateTaskResponse = v1.UpdateTask

// CreateUpdateTaskRequest represents a request to create a UpdateTask
type CreateUpdateTaskRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.UpdateTaskSpec `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateUpdateTaskRequest) AsSpec() v1.UpdateTaskSpec {
	return r.Spec
}

// UpdateUpdateTaskRequest represents a request to update a UpdateTask
type UpdateUpdateTaskRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.UpdateTaskSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateUpdateTaskRequest) AsSpec() v1.UpdateTaskSpec {
	return r.Spec
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
	Code    int    `json:"code,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}

// Helper functions for handlers

// respondJSON sends a JSON response
func respondJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(data); err != nil {
		http.Error(w, fmt.Sprintf("failed to encode response: %v", err), http.StatusInternalServerError)
	}
}

// respondError sends an error response
func respondError(w http.ResponseWriter, status int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	response := ErrorResponse{
		Error: err.Error(),
		Code:  status,
	}
	json.NewEncoder(w).Encode(response)
}
