// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/openapi.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/user/fms/apis/example.fabrica.dev/v1"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OpenCHAMI Inventory API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "OpenCHAMI Inventory API",
			Description: "HPC hardware inventory management system with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "OpenCHAMI Project",
				URL:  "https://github.com/openchami/inventory",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:3333",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerDeviceProfilePaths(spec)
	registerFirmwareProfilePaths(spec)
	registerUpdateJobPaths(spec)
	registerUpdateProfilePaths(spec)

	return spec
}

// registerDeviceProfilePaths registers OpenAPI paths for DeviceProfile resources
func registerDeviceProfilePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.DeviceProfile{}, spec.Components.Schemas)
	spec.Components.Schemas["DeviceProfile"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateDeviceProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateDeviceProfileRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateDeviceProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateDeviceProfileRequest"] = updateReqSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List DeviceProfiles operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listDeviceProfiles"
	listOp.Summary = "List all DeviceProfile resources"
	listOp.Description = "Returns a list of all DeviceProfile resources in the inventory"
	listOp.Tags = []string{"DeviceProfile"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/DeviceProfile"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create DeviceProfile operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createDeviceProfile"
	createOp.Summary = "Create a new DeviceProfile resource"
	createOp.Description = "Creates a new DeviceProfile resource with the provided specification"
	createOp.Tags = []string{"DeviceProfile"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateDeviceProfileRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeviceProfile",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get DeviceProfile operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getDeviceProfile"
	getOp.Summary = "Get a specific DeviceProfile resource"
	getOp.Description = "Returns details of a specific DeviceProfile resource by UID"
	getOp.Tags = []string{"DeviceProfile"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeviceProfile",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update DeviceProfile operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateDeviceProfile"
	updateOp.Summary = "Update a DeviceProfile resource"
	updateOp.Description = "Updates an existing DeviceProfile resource with new values"
	updateOp.Tags = []string{"DeviceProfile"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateDeviceProfileRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeviceProfile",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Delete DeviceProfile operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteDeviceProfile"
	deleteOp.Summary = "Delete a DeviceProfile resource"
	deleteOp.Description = "Removes a DeviceProfile resource from the inventory"
	deleteOp.Tags = []string{"DeviceProfile"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the DeviceProfile resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/deviceprofiles", collectionPath)
	spec.Paths.Set("/deviceprofiles/{uid}", itemPath)
}

// registerFirmwareProfilePaths registers OpenAPI paths for FirmwareProfile resources
func registerFirmwareProfilePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.FirmwareProfile{}, spec.Components.Schemas)
	spec.Components.Schemas["FirmwareProfile"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateFirmwareProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateFirmwareProfileRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateFirmwareProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateFirmwareProfileRequest"] = updateReqSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List FirmwareProfiles operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listFirmwareProfiles"
	listOp.Summary = "List all FirmwareProfile resources"
	listOp.Description = "Returns a list of all FirmwareProfile resources in the inventory"
	listOp.Tags = []string{"FirmwareProfile"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/FirmwareProfile"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create FirmwareProfile operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createFirmwareProfile"
	createOp.Summary = "Create a new FirmwareProfile resource"
	createOp.Description = "Creates a new FirmwareProfile resource with the provided specification"
	createOp.Tags = []string{"FirmwareProfile"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateFirmwareProfileRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/FirmwareProfile",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get FirmwareProfile operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getFirmwareProfile"
	getOp.Summary = "Get a specific FirmwareProfile resource"
	getOp.Description = "Returns details of a specific FirmwareProfile resource by UID"
	getOp.Tags = []string{"FirmwareProfile"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/FirmwareProfile",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update FirmwareProfile operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateFirmwareProfile"
	updateOp.Summary = "Update a FirmwareProfile resource"
	updateOp.Description = "Updates an existing FirmwareProfile resource with new values"
	updateOp.Tags = []string{"FirmwareProfile"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateFirmwareProfileRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/FirmwareProfile",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Delete FirmwareProfile operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteFirmwareProfile"
	deleteOp.Summary = "Delete a FirmwareProfile resource"
	deleteOp.Description = "Removes a FirmwareProfile resource from the inventory"
	deleteOp.Tags = []string{"FirmwareProfile"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the FirmwareProfile resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/firmwareprofiles", collectionPath)
	spec.Paths.Set("/firmwareprofiles/{uid}", itemPath)
}

// registerUpdateJobPaths registers OpenAPI paths for UpdateJob resources
func registerUpdateJobPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.UpdateJob{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateJob"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateUpdateJobRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateUpdateJobRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateUpdateJobRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateUpdateJobRequest"] = updateReqSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List UpdateJobs operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listUpdateJobs"
	listOp.Summary = "List all UpdateJob resources"
	listOp.Description = "Returns a list of all UpdateJob resources in the inventory"
	listOp.Tags = []string{"UpdateJob"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/UpdateJob"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create UpdateJob operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createUpdateJob"
	createOp.Summary = "Create a new UpdateJob resource"
	createOp.Description = "Creates a new UpdateJob resource with the provided specification"
	createOp.Tags = []string{"UpdateJob"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateUpdateJobRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateJob",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get UpdateJob operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getUpdateJob"
	getOp.Summary = "Get a specific UpdateJob resource"
	getOp.Description = "Returns details of a specific UpdateJob resource by UID"
	getOp.Tags = []string{"UpdateJob"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateJob",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update UpdateJob operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateUpdateJob"
	updateOp.Summary = "Update a UpdateJob resource"
	updateOp.Description = "Updates an existing UpdateJob resource with new values"
	updateOp.Tags = []string{"UpdateJob"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateUpdateJobRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateJob",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Delete UpdateJob operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteUpdateJob"
	deleteOp.Summary = "Delete a UpdateJob resource"
	deleteOp.Description = "Removes a UpdateJob resource from the inventory"
	deleteOp.Tags = []string{"UpdateJob"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the UpdateJob resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/updatejobs", collectionPath)
	spec.Paths.Set("/updatejobs/{uid}", itemPath)
}

// registerUpdateProfilePaths registers OpenAPI paths for UpdateProfile resources
func registerUpdateProfilePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.UpdateProfile{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateProfile"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateUpdateProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateUpdateProfileRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateUpdateProfileRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateUpdateProfileRequest"] = updateReqSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List UpdateProfiles operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listUpdateProfiles"
	listOp.Summary = "List all UpdateProfile resources"
	listOp.Description = "Returns a list of all UpdateProfile resources in the inventory"
	listOp.Tags = []string{"UpdateProfile"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/UpdateProfile"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create UpdateProfile operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createUpdateProfile"
	createOp.Summary = "Create a new UpdateProfile resource"
	createOp.Description = "Creates a new UpdateProfile resource with the provided specification"
	createOp.Tags = []string{"UpdateProfile"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateUpdateProfileRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateProfile",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get UpdateProfile operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getUpdateProfile"
	getOp.Summary = "Get a specific UpdateProfile resource"
	getOp.Description = "Returns details of a specific UpdateProfile resource by UID"
	getOp.Tags = []string{"UpdateProfile"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateProfile",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update UpdateProfile operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateUpdateProfile"
	updateOp.Summary = "Update a UpdateProfile resource"
	updateOp.Description = "Updates an existing UpdateProfile resource with new values"
	updateOp.Tags = []string{"UpdateProfile"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateUpdateProfileRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateProfile",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Delete UpdateProfile operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteUpdateProfile"
	deleteOp.Summary = "Delete a UpdateProfile resource"
	deleteOp.Description = "Removes a UpdateProfile resource from the inventory"
	deleteOp.Tags = []string{"UpdateProfile"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the UpdateProfile resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/updateprofiles", collectionPath)
	spec.Paths.Set("/updateprofiles/{uid}", itemPath)
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
