// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /deviceprofiles (DeviceProfile operations)
//   - /firmwaremanifests (FirmwareManifest operations)
//   - /lookupjobs (LookupJob operations)
//   - /updatejobs (UpdateJob operations)
//   - /updateprofiles (UpdateProfile operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("DeviceProfile", "deviceprofile")

	resource.RegisterResourcePrefix("FirmwareManifest", "firmwaremanifest")

	resource.RegisterResourcePrefix("LookupJob", "lookupjob")

	resource.RegisterResourcePrefix("UpdateJob", "updatejob")

	resource.RegisterResourcePrefix("UpdateProfile", "updateprofile")

	return nil
}

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// DeviceProfile routes
	r.Route("/deviceprofiles", func(r chi.Router) {
		r.Get("/", GetDeviceProfiles)
		r.Post("/", CreateDeviceProfile)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetDeviceProfile)
			r.Put("/", UpdateDeviceProfile)
			r.Patch("/", PatchDeviceProfile)
			r.Delete("/", DeleteDeviceProfile)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateDeviceProfileStatus)
				r.Patch("/", PatchDeviceProfileStatus)
			})
		})
	})

	// FirmwareManifest routes
	r.Route("/firmwaremanifests", func(r chi.Router) {
		r.Get("/", GetFirmwareManifests)
		r.Post("/", CreateFirmwareManifest)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetFirmwareManifest)
			r.Put("/", UpdateFirmwareManifest)
			r.Patch("/", PatchFirmwareManifest)
			r.Delete("/", DeleteFirmwareManifest)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateFirmwareManifestStatus)
				r.Patch("/", PatchFirmwareManifestStatus)
			})
		})
	})

	// LookupJob routes
	r.Route("/lookupjobs", func(r chi.Router) {
		r.Get("/", GetLookupJobs)
		r.Post("/", CreateLookupJob)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetLookupJob)
			r.Put("/", UpdateLookupJob)
			r.Patch("/", PatchLookupJob)
			r.Delete("/", DeleteLookupJob)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateLookupJobStatus)
				r.Patch("/", PatchLookupJobStatus)
			})
		})
	})

	// UpdateJob routes
	r.Route("/updatejobs", func(r chi.Router) {
		r.Get("/", GetUpdateJobs)
		r.Post("/", CreateUpdateJob)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetUpdateJob)
			r.Put("/", UpdateUpdateJob)
			r.Patch("/", PatchUpdateJob)
			r.Delete("/", DeleteUpdateJob)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateUpdateJobStatus)
				r.Patch("/", PatchUpdateJobStatus)
			})
		})
	})

	// UpdateProfile routes
	r.Route("/updateprofiles", func(r chi.Router) {
		r.Get("/", GetUpdateProfiles)
		r.Post("/", CreateUpdateProfile)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetUpdateProfile)
			r.Put("/", UpdateUpdateProfile)
			r.Patch("/", PatchUpdateProfile)
			r.Delete("/", DeleteUpdateProfile)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateUpdateProfileStatus)
				r.Patch("/", PatchUpdateProfileStatus)
			})
		})
	})

	// OpenAPI documentation routes
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)
}
