// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-15T15:29:17-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for UpdateProfile resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /updateprofiles (list all updateprofiles)
//   - GET /updateprofiles/{uid} (get specific UpdateProfile)
//   - POST /updateprofiles (create new UpdateProfile)
//   - PUT /updateprofiles/{uid} (update UpdateProfile spec)
//   - PATCH /updateprofiles/{uid} (patch UpdateProfile spec)
//   - DELETE /updateprofiles/{uid} (delete UpdateProfile)
//   - PUT /updateprofiles/{uid}/status (update UpdateProfile status)
//   - PATCH /updateprofiles/{uid}/status (patch UpdateProfile status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadUpdateProfile*/SaveUpdateProfile*/DeleteUpdateProfile*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadUpdateProfileWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/firmware-management-service/fms/apis/firmware.management.io/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/firmware-management-service/fms/internal/storage"
)

// GetUpdateProfiles returns all UpdateProfile resources
func GetUpdateProfiles(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updateprofiles, err := storage.LoadAllUpdateProfiles(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load updateprofiles: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updateprofiles)
}

// GetUpdateProfile returns a specific UpdateProfile resource by UID
func GetUpdateProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadUpdateProfile() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updateProfile, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updateProfile)
}

// CreateUpdateProfile creates a new UpdateProfile resource
func CreateUpdateProfile(w http.ResponseWriter, r *http.Request) {
	var req CreateUpdateProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("UpdateProfile")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	updateProfile := &v1.UpdateProfile{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "UpdateProfile",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	updateProfile.Metadata = req.Metadata
	updateProfile.Metadata.UID = uid
	now := time.Now()
	updateProfile.Metadata.CreatedAt = now
	updateProfile.Metadata.UpdatedAt = now

	// Set labels and annotations
	if updateProfile.Metadata.Labels == nil {
		updateProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateProfile.Metadata.Labels[k] = v
	}
	if updateProfile.Metadata.Annotations == nil {
		updateProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateProfile.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), updateProfile); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveUpdateProfile(r.Context(), updateProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateProfile: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "UpdateProfile", updateProfile.Metadata.UID, updateProfile.Metadata.Name, updateProfile); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for UpdateProfile %s: %v\n", updateProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, updateProfile)
}

// UpdateUpdateProfile updates the spec of an existing UpdateProfile resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //updateprofiles/{uid}/status to update status.
func UpdateUpdateProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	updateProfile, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}

	var req UpdateUpdateProfileRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		updateProfile.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	updateProfile.Spec = req.AsSpec()

	// Update labels and annotations
	if updateProfile.Metadata.Labels == nil {
		updateProfile.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateProfile.Metadata.Labels[k] = v
	}
	if updateProfile.Metadata.Annotations == nil {
		updateProfile.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateProfile.Metadata.Annotations[k] = v
	}

	// Update timestamp
	updateProfile.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateProfile(r.Context(), updateProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateProfile: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": updateProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateProfile", updateProfile.Metadata.UID, updateProfile.Metadata.Name, updateProfile, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for UpdateProfile %s: %v\n", updateProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateProfile)
}

// PatchUpdateProfile patches an existing UpdateProfile resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchUpdateProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	updateProfile, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(updateProfile.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &updateProfile.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	updateProfile.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveUpdateProfile(r.Context(), updateProfile); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateProfile: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": updateProfile.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateProfile", updateProfile.Metadata.UID, updateProfile.Metadata.Name, updateProfile, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for UpdateProfile %s: %v\n", updateProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateProfile)
}

// UpdateUpdateProfileStatus updates only the status of a UpdateProfile resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateUpdateProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}

	var statusUpdate v1.UpdateProfileStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateProfile status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateProfile", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for UpdateProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchUpdateProfileStatus patches only the status of a UpdateProfile resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchUpdateProfileStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateProfile(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateProfile status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateProfile", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for UpdateProfile %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteUpdateProfile deletes a UpdateProfile resource
func DeleteUpdateProfile(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateProfile UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	updateProfile, err := storage.LoadUpdateProfile(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateProfile not found: %w", err))
		return
	}

	if err := storage.DeleteUpdateProfile(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete UpdateProfile: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "UpdateProfile", updateProfile.Metadata.UID, updateProfile.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for UpdateProfile %s: %v\n", updateProfile.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "UpdateProfile deleted successfully",
		UID:     uid,
	})
}
