// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-20T13:20:44-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for UpdateTask resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /updatetasks (list all updatetasks)
//   - GET /updatetasks/{uid} (get specific UpdateTask)
//   - POST /updatetasks (create new UpdateTask)
//   - PUT /updatetasks/{uid} (update UpdateTask spec)
//   - PATCH /updatetasks/{uid} (patch UpdateTask spec)
//   - DELETE /updatetasks/{uid} (delete UpdateTask)
//   - PUT /updatetasks/{uid}/status (update UpdateTask status)
//   - PATCH /updatetasks/{uid}/status (patch UpdateTask status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadUpdateTask*/SaveUpdateTask*/DeleteUpdateTask*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadUpdateTaskWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/bmcdonald3/fms/apis/example.fabrica.dev/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/bmcdonald3/fms/internal/storage"
)

// GetUpdateTasks returns all UpdateTask resources
func GetUpdateTasks(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updatetasks, err := storage.LoadAllUpdateTasks(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load updatetasks: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updatetasks)
}

// GetUpdateTask returns a specific UpdateTask resource by UID
func GetUpdateTask(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadUpdateTask() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updateTask, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updateTask)
}

// CreateUpdateTask creates a new UpdateTask resource
func CreateUpdateTask(w http.ResponseWriter, r *http.Request) {
	var req CreateUpdateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("UpdateTask")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	updateTask := &v1.UpdateTask{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "UpdateTask",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	updateTask.Metadata = req.Metadata
	updateTask.Metadata.UID = uid
	now := time.Now()
	updateTask.Metadata.CreatedAt = now
	updateTask.Metadata.UpdatedAt = now

	// Set labels and annotations
	if updateTask.Metadata.Labels == nil {
		updateTask.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateTask.Metadata.Labels[k] = v
	}
	if updateTask.Metadata.Annotations == nil {
		updateTask.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateTask.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), updateTask); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveUpdateTask(r.Context(), updateTask); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateTask: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "UpdateTask", updateTask.Metadata.UID, updateTask.Metadata.Name, updateTask); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for UpdateTask %s: %v\n", updateTask.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, updateTask)
}

// UpdateUpdateTask updates the spec of an existing UpdateTask resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //updatetasks/{uid}/status to update status.
func UpdateUpdateTask(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	updateTask, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}

	var req UpdateUpdateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		updateTask.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	updateTask.Spec = req.AsSpec()

	// Update labels and annotations
	if updateTask.Metadata.Labels == nil {
		updateTask.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateTask.Metadata.Labels[k] = v
	}
	if updateTask.Metadata.Annotations == nil {
		updateTask.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateTask.Metadata.Annotations[k] = v
	}

	// Update timestamp
	updateTask.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateTask(r.Context(), updateTask); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateTask: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": updateTask.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateTask", updateTask.Metadata.UID, updateTask.Metadata.Name, updateTask, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for UpdateTask %s: %v\n", updateTask.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateTask)
}

// PatchUpdateTask patches an existing UpdateTask resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchUpdateTask(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	updateTask, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(updateTask.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &updateTask.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	updateTask.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveUpdateTask(r.Context(), updateTask); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateTask: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": updateTask.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateTask", updateTask.Metadata.UID, updateTask.Metadata.Name, updateTask, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for UpdateTask %s: %v\n", updateTask.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateTask)
}

// UpdateUpdateTaskStatus updates only the status of a UpdateTask resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateUpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}

	var statusUpdate v1.UpdateTaskStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateTask(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateTask status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateTask", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for UpdateTask %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchUpdateTaskStatus patches only the status of a UpdateTask resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchUpdateTaskStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateTask(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateTask status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateTask", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for UpdateTask %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteUpdateTask deletes a UpdateTask resource
func DeleteUpdateTask(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateTask UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	updateTask, err := storage.LoadUpdateTask(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateTask not found: %w", err))
		return
	}

	if err := storage.DeleteUpdateTask(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete UpdateTask: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "UpdateTask", updateTask.Metadata.UID, updateTask.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for UpdateTask %s: %v\n", updateTask.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "UpdateTask deleted successfully",
		UID:     uid,
	})
}
