// Code generated by fabrica generate. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides storage convenience functions for your resources.
// It uses the fabrica storage backend system.
//
// To modify storage behavior:
//  1. Edit pkg/codegen/templates/storage.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//
// To change storage backend:
//  1. Call storage.Init() with a different backend in main.go
//  2. Options: FileBackend, EntBackend (database), or custom backend
package storage

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openchami/fabrica/pkg/reconcile"
	fabricaStorage "github.com/openchami/fabrica/pkg/storage"

	"github.com/user/fms/apis/example.fabrica.dev/v1"
)

// Backend is the storage backend used by all storage operations.
// Initialize this in your main.go before using any storage functions.
//
// Example:
//
//	backend, err := fabricaStorage.NewFileBackend("./data")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	storage.Init(backend)
var Backend fabricaStorage.StorageBackend

// Init initializes the storage backend.
// This must be called before using any storage functions.
func Init(backend fabricaStorage.StorageBackend) {
	Backend = backend
}

// InitFileBackend is a convenience function to initialize file-based storage.
// It creates the directory if it doesn't exist.
func InitFileBackend(dataDir string) error {
	backend, err := fabricaStorage.NewFileBackend(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create file backend: %w", err)
	}
	Backend = backend
	return nil
}

// ensureBackend panics if Backend is not initialized.
// This is called by all storage functions to ensure proper initialization.
func ensureBackend() {
	if Backend == nil {
		panic("storage backend not initialized: call storage.Init() or storage.InitFileBackend() in main.go")
	}
}

// DeviceProfile storage operations

// LoadAllDeviceProfiles retrieves all DeviceProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.DeviceProfile: Slice of DeviceProfile resources
//   - error: Any error that occurred during loading
func LoadAllDeviceProfiles(ctx context.Context) ([]*v1.DeviceProfile, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "DeviceProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to load all deviceprofiles: %w", err)
	}

	deviceprofiles := make([]*v1.DeviceProfile, 0, len(rawData))
	for _, raw := range rawData {
		deviceProfile := &v1.DeviceProfile{}
		if err := json.Unmarshal(raw, deviceProfile); err != nil {
			return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
		}
		deviceprofiles = append(deviceprofiles, deviceProfile)
	}

	return deviceprofiles, nil
}

// LoadDeviceProfile retrieves a single DeviceProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the DeviceProfile resource
//
// Returns:
//   - *v1.DeviceProfile: The DeviceProfile resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadDeviceProfile(ctx context.Context, uid string) (*v1.DeviceProfile, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "DeviceProfile", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load DeviceProfile %s: %w", uid, err)
	}

	deviceProfile := &v1.DeviceProfile{}
	if err := json.Unmarshal(rawData, deviceProfile); err != nil {
		return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
	}

	return deviceProfile, nil
}

// SaveDeviceProfile stores a DeviceProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - deviceProfile: The DeviceProfile resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveDeviceProfile(ctx context.Context, deviceProfile *v1.DeviceProfile) error {
	ensureBackend()

	data, err := json.Marshal(deviceProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal DeviceProfile: %w", err)
	}

	if err := Backend.Save(ctx, "DeviceProfile", deviceProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save DeviceProfile: %w", err)
	}

	return nil
}

// UpdateDeviceProfile updates an existing DeviceProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - deviceProfile: The DeviceProfile resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateDeviceProfile(ctx context.Context, deviceProfile *v1.DeviceProfile) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "DeviceProfile", deviceProfile.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check DeviceProfile existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(deviceProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal DeviceProfile: %w", err)
	}

	if err := Backend.Save(ctx, "DeviceProfile", deviceProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update DeviceProfile: %w", err)
	}

	return nil
}

// DeleteDeviceProfile removes a DeviceProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the DeviceProfile resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteDeviceProfile(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "DeviceProfile", uid); err != nil {
		return fmt.Errorf("failed to delete DeviceProfile %s: %w", uid, err)
	}

	return nil
}

// ExistsDeviceProfile checks if a DeviceProfile resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the DeviceProfile resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsDeviceProfile(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "DeviceProfile", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check DeviceProfile existence: %w", err)
	}

	return exists, nil
}

// ListDeviceProfileUIDs returns UIDs of all DeviceProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of DeviceProfile resource UIDs
//   - error: Any error that occurred during listing
func ListDeviceProfileUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "DeviceProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to list DeviceProfile UIDs: %w", err)
	}

	return uids, nil
}

// FirmwareProfile storage operations

// LoadAllFirmwareProfiles retrieves all FirmwareProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.FirmwareProfile: Slice of FirmwareProfile resources
//   - error: Any error that occurred during loading
func LoadAllFirmwareProfiles(ctx context.Context) ([]*v1.FirmwareProfile, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "FirmwareProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to load all firmwareprofiles: %w", err)
	}

	firmwareprofiles := make([]*v1.FirmwareProfile, 0, len(rawData))
	for _, raw := range rawData {
		firmwareProfile := &v1.FirmwareProfile{}
		if err := json.Unmarshal(raw, firmwareProfile); err != nil {
			return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
		}
		firmwareprofiles = append(firmwareprofiles, firmwareProfile)
	}

	return firmwareprofiles, nil
}

// LoadFirmwareProfile retrieves a single FirmwareProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the FirmwareProfile resource
//
// Returns:
//   - *v1.FirmwareProfile: The FirmwareProfile resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadFirmwareProfile(ctx context.Context, uid string) (*v1.FirmwareProfile, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "FirmwareProfile", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load FirmwareProfile %s: %w", uid, err)
	}

	firmwareProfile := &v1.FirmwareProfile{}
	if err := json.Unmarshal(rawData, firmwareProfile); err != nil {
		return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
	}

	return firmwareProfile, nil
}

// SaveFirmwareProfile stores a FirmwareProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - firmwareProfile: The FirmwareProfile resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveFirmwareProfile(ctx context.Context, firmwareProfile *v1.FirmwareProfile) error {
	ensureBackend()

	data, err := json.Marshal(firmwareProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal FirmwareProfile: %w", err)
	}

	if err := Backend.Save(ctx, "FirmwareProfile", firmwareProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save FirmwareProfile: %w", err)
	}

	return nil
}

// UpdateFirmwareProfile updates an existing FirmwareProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - firmwareProfile: The FirmwareProfile resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateFirmwareProfile(ctx context.Context, firmwareProfile *v1.FirmwareProfile) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "FirmwareProfile", firmwareProfile.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check FirmwareProfile existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(firmwareProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal FirmwareProfile: %w", err)
	}

	if err := Backend.Save(ctx, "FirmwareProfile", firmwareProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update FirmwareProfile: %w", err)
	}

	return nil
}

// DeleteFirmwareProfile removes a FirmwareProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the FirmwareProfile resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteFirmwareProfile(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "FirmwareProfile", uid); err != nil {
		return fmt.Errorf("failed to delete FirmwareProfile %s: %w", uid, err)
	}

	return nil
}

// ExistsFirmwareProfile checks if a FirmwareProfile resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the FirmwareProfile resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsFirmwareProfile(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "FirmwareProfile", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check FirmwareProfile existence: %w", err)
	}

	return exists, nil
}

// ListFirmwareProfileUIDs returns UIDs of all FirmwareProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of FirmwareProfile resource UIDs
//   - error: Any error that occurred during listing
func ListFirmwareProfileUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "FirmwareProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to list FirmwareProfile UIDs: %w", err)
	}

	return uids, nil
}

// UpdateJob storage operations

// LoadAllUpdateJobs retrieves all UpdateJob resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.UpdateJob: Slice of UpdateJob resources
//   - error: Any error that occurred during loading
func LoadAllUpdateJobs(ctx context.Context) ([]*v1.UpdateJob, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "UpdateJob")
	if err != nil {
		return nil, fmt.Errorf("failed to load all updatejobs: %w", err)
	}

	updatejobs := make([]*v1.UpdateJob, 0, len(rawData))
	for _, raw := range rawData {
		updateJob := &v1.UpdateJob{}
		if err := json.Unmarshal(raw, updateJob); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
		}
		updatejobs = append(updatejobs, updateJob)
	}

	return updatejobs, nil
}

// LoadUpdateJob retrieves a single UpdateJob resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateJob resource
//
// Returns:
//   - *v1.UpdateJob: The UpdateJob resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadUpdateJob(ctx context.Context, uid string) (*v1.UpdateJob, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "UpdateJob", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load UpdateJob %s: %w", uid, err)
	}

	updateJob := &v1.UpdateJob{}
	if err := json.Unmarshal(rawData, updateJob); err != nil {
		return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
	}

	return updateJob, nil
}

// SaveUpdateJob stores a UpdateJob resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - updateJob: The UpdateJob resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveUpdateJob(ctx context.Context, updateJob *v1.UpdateJob) error {
	ensureBackend()

	data, err := json.Marshal(updateJob)
	if err != nil {
		return fmt.Errorf("failed to marshal UpdateJob: %w", err)
	}

	if err := Backend.Save(ctx, "UpdateJob", updateJob.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save UpdateJob: %w", err)
	}

	return nil
}

// UpdateUpdateJob updates an existing UpdateJob resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - updateJob: The UpdateJob resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateUpdateJob(ctx context.Context, updateJob *v1.UpdateJob) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "UpdateJob", updateJob.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check UpdateJob existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(updateJob)
	if err != nil {
		return fmt.Errorf("failed to marshal UpdateJob: %w", err)
	}

	if err := Backend.Save(ctx, "UpdateJob", updateJob.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update UpdateJob: %w", err)
	}

	return nil
}

// DeleteUpdateJob removes a UpdateJob resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateJob resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteUpdateJob(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "UpdateJob", uid); err != nil {
		return fmt.Errorf("failed to delete UpdateJob %s: %w", uid, err)
	}

	return nil
}

// ExistsUpdateJob checks if a UpdateJob resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateJob resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsUpdateJob(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "UpdateJob", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check UpdateJob existence: %w", err)
	}

	return exists, nil
}

// ListUpdateJobUIDs returns UIDs of all UpdateJob resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of UpdateJob resource UIDs
//   - error: Any error that occurred during listing
func ListUpdateJobUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "UpdateJob")
	if err != nil {
		return nil, fmt.Errorf("failed to list UpdateJob UIDs: %w", err)
	}

	return uids, nil
}

// UpdateProfile storage operations

// LoadAllUpdateProfiles retrieves all UpdateProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.UpdateProfile: Slice of UpdateProfile resources
//   - error: Any error that occurred during loading
func LoadAllUpdateProfiles(ctx context.Context) ([]*v1.UpdateProfile, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "UpdateProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to load all updateprofiles: %w", err)
	}

	updateprofiles := make([]*v1.UpdateProfile, 0, len(rawData))
	for _, raw := range rawData {
		updateProfile := &v1.UpdateProfile{}
		if err := json.Unmarshal(raw, updateProfile); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
		}
		updateprofiles = append(updateprofiles, updateProfile)
	}

	return updateprofiles, nil
}

// LoadUpdateProfile retrieves a single UpdateProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateProfile resource
//
// Returns:
//   - *v1.UpdateProfile: The UpdateProfile resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadUpdateProfile(ctx context.Context, uid string) (*v1.UpdateProfile, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "UpdateProfile", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load UpdateProfile %s: %w", uid, err)
	}

	updateProfile := &v1.UpdateProfile{}
	if err := json.Unmarshal(rawData, updateProfile); err != nil {
		return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
	}

	return updateProfile, nil
}

// SaveUpdateProfile stores a UpdateProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - updateProfile: The UpdateProfile resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveUpdateProfile(ctx context.Context, updateProfile *v1.UpdateProfile) error {
	ensureBackend()

	data, err := json.Marshal(updateProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal UpdateProfile: %w", err)
	}

	if err := Backend.Save(ctx, "UpdateProfile", updateProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save UpdateProfile: %w", err)
	}

	return nil
}

// UpdateUpdateProfile updates an existing UpdateProfile resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - updateProfile: The UpdateProfile resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateUpdateProfile(ctx context.Context, updateProfile *v1.UpdateProfile) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "UpdateProfile", updateProfile.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check UpdateProfile existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(updateProfile)
	if err != nil {
		return fmt.Errorf("failed to marshal UpdateProfile: %w", err)
	}

	if err := Backend.Save(ctx, "UpdateProfile", updateProfile.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update UpdateProfile: %w", err)
	}

	return nil
}

// DeleteUpdateProfile removes a UpdateProfile resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateProfile resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteUpdateProfile(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "UpdateProfile", uid); err != nil {
		return fmt.Errorf("failed to delete UpdateProfile %s: %w", uid, err)
	}

	return nil
}

// ExistsUpdateProfile checks if a UpdateProfile resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the UpdateProfile resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsUpdateProfile(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "UpdateProfile", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check UpdateProfile existence: %w", err)
	}

	return exists, nil
}

// ListUpdateProfileUIDs returns UIDs of all UpdateProfile resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of UpdateProfile resource UIDs
//   - error: Any error that occurred during listing
func ListUpdateProfileUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "UpdateProfile")
	if err != nil {
		return nil, fmt.Errorf("failed to list UpdateProfile UIDs: %w", err)
	}

	return uids, nil
}

// StorageClient wraps a StorageBackend to implement reconcile.ClientInterface.
//
// This adapter allows reconcilers to use the storage backend through a
// standard interface that provides typed resource access.
type StorageClient struct {
	backend fabricaStorage.StorageBackend
}

// Compile-time check that StorageClient implements reconcile.ClientInterface
var _ reconcile.ClientInterface = (*StorageClient)(nil)

// NewStorageClient creates a new storage client that wraps the configured backend.
//
// This is used by the reconciliation system to provide reconcilers with
// access to resource storage.
//
// Returns:
//   - *StorageClient: Client that implements reconcile.ClientInterface
func NewStorageClient() *StorageClient {
	ensureBackend()
	return &StorageClient{backend: Backend}
}

// --- Version snapshot helpers (file backend only) ---

// Get retrieves a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//   - uid: Unique identifier
//
// Returns:
//   - interface{}: The resource (type-specific)
//   - error: Any error that occurred
func (c *StorageClient) Get(ctx context.Context, kind, uid string) (interface{}, error) {
	rawData, err := c.backend.Load(ctx, kind, uid)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "DeviceProfile":
		var resource v1.DeviceProfile
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
		}
		return &resource, nil
	case "FirmwareProfile":
		var resource v1.FirmwareProfile
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
		}
		return &resource, nil
	case "UpdateJob":
		var resource v1.UpdateJob
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
		}
		return &resource, nil
	case "UpdateProfile":
		var resource v1.UpdateProfile
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
		}
		return &resource, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// List retrieves all resources of a given kind.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//
// Returns:
//   - []interface{}: Slice of resources
//   - error: Any error that occurred
func (c *StorageClient) List(ctx context.Context, kind string) ([]interface{}, error) {
	rawData, err := c.backend.LoadAll(ctx, kind)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "DeviceProfile":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.DeviceProfile
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "FirmwareProfile":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.FirmwareProfile
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "UpdateJob":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.UpdateJob
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "UpdateProfile":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.UpdateProfile
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// Update updates an existing resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to update
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Update(ctx context.Context, resource interface{}) error {
	data, err := json.Marshal(resource)
	if err != nil {
		return fmt.Errorf("failed to marshal resource: %w", err)
	}

	// Extract kind and UID based on type
	switch res := resource.(type) {
	case *v1.DeviceProfile:
		return c.backend.Save(ctx, "DeviceProfile", res.Metadata.UID, data)
	case *v1.FirmwareProfile:
		return c.backend.Save(ctx, "FirmwareProfile", res.Metadata.UID, data)
	case *v1.UpdateJob:
		return c.backend.Save(ctx, "UpdateJob", res.Metadata.UID, data)
	case *v1.UpdateProfile:
		return c.backend.Save(ctx, "UpdateProfile", res.Metadata.UID, data)
	default:
		return fmt.Errorf("unknown resource type: %T", resource)
	}
}

// Create creates a new resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to create
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Create(ctx context.Context, resource interface{}) error {
	// For storage backend, Create is the same as Update (Save handles both)
	return c.Update(ctx, resource)
}

// Delete deletes a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind
//   - uid: Unique identifier
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Delete(ctx context.Context, kind, uid string) error {
	return c.backend.Delete(ctx, kind, uid)
}
