// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides storage functions using Ent as the backend.
// The functions maintain the same interface as file storage for compatibility.

package storage

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/openchami/fabrica/pkg/reconcile"
	fabricaStorage "github.com/openchami/fabrica/pkg/storage"

	"github.com/bmcdonald3/fms/internal/storage/ent"
	entresource "github.com/bmcdonald3/fms/internal/storage/ent/resource"

	v1 "github.com/bmcdonald3/fms/apis/example.fabrica.dev/v1"
)

// ErrNotFound indicates that a resource was not found
var ErrNotFound = errors.New("resource not found")

// Ent client (initialized in main.go)
var entClient *ent.Client

// SetEntClient sets the Ent client for storage operations
func SetEntClient(client *ent.Client) {
	entClient = client
}

// LoadAllDeviceProfiles loads all DeviceProfile resources from Ent storage
func LoadAllDeviceProfiles(ctx context.Context) ([]*v1.DeviceProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("DeviceProfile")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load DeviceProfile resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.DeviceProfile
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.DeviceProfile))
	}

	return resources, nil
}

// LoadDeviceProfile loads a single DeviceProfile resource by UID from Ent storage
func LoadDeviceProfile(ctx context.Context, uid string) (*v1.DeviceProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("DeviceProfile"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load DeviceProfile %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.DeviceProfile), nil
}

// SaveDeviceProfile saves a DeviceProfile resource to Ent storage
func SaveDeviceProfile(ctx context.Context, resource *v1.DeviceProfile) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert DeviceProfile to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check DeviceProfile existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create DeviceProfile: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update DeviceProfile: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteDeviceProfile deletes a DeviceProfile resource from Ent storage
func DeleteDeviceProfile(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("DeviceProfile"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete DeviceProfile %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllFirmwareProfiles loads all FirmwareProfile resources from Ent storage
func LoadAllFirmwareProfiles(ctx context.Context) ([]*v1.FirmwareProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("FirmwareProfile")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load FirmwareProfile resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.FirmwareProfile
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.FirmwareProfile))
	}

	return resources, nil
}

// LoadFirmwareProfile loads a single FirmwareProfile resource by UID from Ent storage
func LoadFirmwareProfile(ctx context.Context, uid string) (*v1.FirmwareProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("FirmwareProfile"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load FirmwareProfile %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.FirmwareProfile), nil
}

// SaveFirmwareProfile saves a FirmwareProfile resource to Ent storage
func SaveFirmwareProfile(ctx context.Context, resource *v1.FirmwareProfile) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert FirmwareProfile to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check FirmwareProfile existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create FirmwareProfile: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update FirmwareProfile: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteFirmwareProfile deletes a FirmwareProfile resource from Ent storage
func DeleteFirmwareProfile(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("FirmwareProfile"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete FirmwareProfile %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllLookupJobs loads all LookupJob resources from Ent storage
func LoadAllLookupJobs(ctx context.Context) ([]*v1.LookupJob, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("LookupJob")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load LookupJob resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.LookupJob
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.LookupJob))
	}

	return resources, nil
}

// LoadLookupJob loads a single LookupJob resource by UID from Ent storage
func LoadLookupJob(ctx context.Context, uid string) (*v1.LookupJob, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("LookupJob"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load LookupJob %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.LookupJob), nil
}

// SaveLookupJob saves a LookupJob resource to Ent storage
func SaveLookupJob(ctx context.Context, resource *v1.LookupJob) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert LookupJob to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check LookupJob existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create LookupJob: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update LookupJob: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteLookupJob deletes a LookupJob resource from Ent storage
func DeleteLookupJob(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("LookupJob"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete LookupJob %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllUpdateJobs loads all UpdateJob resources from Ent storage
func LoadAllUpdateJobs(ctx context.Context) ([]*v1.UpdateJob, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("UpdateJob")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load UpdateJob resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.UpdateJob
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.UpdateJob))
	}

	return resources, nil
}

// LoadUpdateJob loads a single UpdateJob resource by UID from Ent storage
func LoadUpdateJob(ctx context.Context, uid string) (*v1.UpdateJob, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateJob"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load UpdateJob %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.UpdateJob), nil
}

// SaveUpdateJob saves a UpdateJob resource to Ent storage
func SaveUpdateJob(ctx context.Context, resource *v1.UpdateJob) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert UpdateJob to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check UpdateJob existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create UpdateJob: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update UpdateJob: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteUpdateJob deletes a UpdateJob resource from Ent storage
func DeleteUpdateJob(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateJob"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete UpdateJob %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllUpdateProfiles loads all UpdateProfile resources from Ent storage
func LoadAllUpdateProfiles(ctx context.Context) ([]*v1.UpdateProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("UpdateProfile")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load UpdateProfile resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.UpdateProfile
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.UpdateProfile))
	}

	return resources, nil
}

// LoadUpdateProfile loads a single UpdateProfile resource by UID from Ent storage
func LoadUpdateProfile(ctx context.Context, uid string) (*v1.UpdateProfile, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateProfile"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load UpdateProfile %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.UpdateProfile), nil
}

// SaveUpdateProfile saves a UpdateProfile resource to Ent storage
func SaveUpdateProfile(ctx context.Context, resource *v1.UpdateProfile) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert UpdateProfile to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check UpdateProfile existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create UpdateProfile: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update UpdateProfile: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteUpdateProfile deletes a UpdateProfile resource from Ent storage
func DeleteUpdateProfile(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateProfile"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete UpdateProfile %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllUpdateTasks loads all UpdateTask resources from Ent storage
func LoadAllUpdateTasks(ctx context.Context) ([]*v1.UpdateTask, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("UpdateTask")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load UpdateTask resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.UpdateTask
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.UpdateTask))
	}

	return resources, nil
}

// LoadUpdateTask loads a single UpdateTask resource by UID from Ent storage
func LoadUpdateTask(ctx context.Context, uid string) (*v1.UpdateTask, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateTask"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load UpdateTask %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.UpdateTask), nil
}

// SaveUpdateTask saves a UpdateTask resource to Ent storage
func SaveUpdateTask(ctx context.Context, resource *v1.UpdateTask) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert UpdateTask to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check UpdateTask existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create UpdateTask: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		savedResource, err = entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now()).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update UpdateTask: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteUpdateTask deletes a UpdateTask resource from Ent storage
func DeleteUpdateTask(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("UpdateTask"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete UpdateTask %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

var Backend fabricaStorage.StorageBackend = &entStorageBackend{}

var _ fabricaStorage.StorageBackend = (*entStorageBackend)(nil)

type entStorageBackend struct{}

func ensureBackendReady() error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}
	return nil
}

func (b *entStorageBackend) LoadAll(ctx context.Context, resourceType string) ([]json.RawMessage, error) {
	if err := ensureBackendReady(); err != nil {
		return nil, err
	}
	switch resourceType {
	case "DeviceProfile":
		resources, err := LoadAllDeviceProfiles(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "FirmwareProfile":
		resources, err := LoadAllFirmwareProfiles(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "LookupJob":
		resources, err := LoadAllLookupJobs(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "UpdateJob":
		resources, err := LoadAllUpdateJobs(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "UpdateProfile":
		resources, err := LoadAllUpdateProfiles(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "UpdateTask":
		resources, err := LoadAllUpdateTasks(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	default:
		return nil, fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Load(ctx context.Context, resourceType, uid string) (json.RawMessage, error) {
	if err := ensureBackendReady(); err != nil {
		return nil, err
	}
	switch resourceType {
	case "DeviceProfile":
		resource, err := LoadDeviceProfile(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "FirmwareProfile":
		resource, err := LoadFirmwareProfile(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "LookupJob":
		resource, err := LoadLookupJob(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "UpdateJob":
		resource, err := LoadUpdateJob(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "UpdateProfile":
		resource, err := LoadUpdateProfile(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "UpdateTask":
		resource, err := LoadUpdateTask(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	default:
		return nil, fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Save(ctx context.Context, resourceType, uid string, data json.RawMessage) error {
	if err := ensureBackendReady(); err != nil {
		return err
	}
	switch resourceType {
	case "DeviceProfile":
		var res v1.DeviceProfile
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
		}
		res.Metadata.UID = uid
		return SaveDeviceProfile(ctx, &res)
	case "FirmwareProfile":
		var res v1.FirmwareProfile
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
		}
		res.Metadata.UID = uid
		return SaveFirmwareProfile(ctx, &res)
	case "LookupJob":
		var res v1.LookupJob
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal LookupJob: %w", err)
		}
		res.Metadata.UID = uid
		return SaveLookupJob(ctx, &res)
	case "UpdateJob":
		var res v1.UpdateJob
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
		}
		res.Metadata.UID = uid
		return SaveUpdateJob(ctx, &res)
	case "UpdateProfile":
		var res v1.UpdateProfile
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
		}
		res.Metadata.UID = uid
		return SaveUpdateProfile(ctx, &res)
	case "UpdateTask":
		var res v1.UpdateTask
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal UpdateTask: %w", err)
		}
		res.Metadata.UID = uid
		return SaveUpdateTask(ctx, &res)
	default:
		return fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Delete(ctx context.Context, resourceType, uid string) error {
	if err := ensureBackendReady(); err != nil {
		return err
	}
	switch resourceType {
	case "DeviceProfile":
		return DeleteDeviceProfile(ctx, uid)
	case "FirmwareProfile":
		return DeleteFirmwareProfile(ctx, uid)
	case "LookupJob":
		return DeleteLookupJob(ctx, uid)
	case "UpdateJob":
		return DeleteUpdateJob(ctx, uid)
	case "UpdateProfile":
		return DeleteUpdateProfile(ctx, uid)
	case "UpdateTask":
		return DeleteUpdateTask(ctx, uid)
	default:
		return fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Exists(ctx context.Context, resourceType, uid string) (bool, error) {
	_, err := b.Load(ctx, resourceType, uid)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

func (b *entStorageBackend) List(ctx context.Context, resourceType string) ([]string, error) {
	items, err := b.LoadAll(ctx, resourceType)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, item := range items {
		uid, err := extractUID(item)
		if err != nil {
			return nil, err
		}
		out = append(out, uid)
	}
	return out, nil
}

func (b *entStorageBackend) LoadWithVersion(ctx context.Context, resourceType, uid, version string) (json.RawMessage, string, error) {
	data, err := b.Load(ctx, resourceType, uid)
	if err != nil {
		return nil, "", err
	}
	if version == "" {
		version = ""
	}
	return data, version, nil
}

func (b *entStorageBackend) LoadAllWithVersion(ctx context.Context, resourceType, version string) ([]json.RawMessage, error) {
	return b.LoadAll(ctx, resourceType)
}

func (b *entStorageBackend) SaveWithVersion(ctx context.Context, resourceType, uid string, data json.RawMessage, version string) error {
	return b.Save(ctx, resourceType, uid, data)
}

func (b *entStorageBackend) Close() error {
	return nil
}

type StorageClient struct {
	backend fabricaStorage.StorageBackend
}

var _ reconcile.ClientInterface = (*StorageClient)(nil)

func NewStorageClient() *StorageClient {
	if err := ensureBackendReady(); err != nil {
		panic(err)
	}
	return &StorageClient{backend: Backend}
}

func (c *StorageClient) Get(ctx context.Context, kind, uid string) (interface{}, error) {
	raw, err := c.backend.Load(ctx, kind, uid)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "DeviceProfile":
		var resource v1.DeviceProfile
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
		}
		return &resource, nil
	case "FirmwareProfile":
		var resource v1.FirmwareProfile
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
		}
		return &resource, nil
	case "LookupJob":
		var resource v1.LookupJob
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal LookupJob: %w", err)
		}
		return &resource, nil
	case "UpdateJob":
		var resource v1.UpdateJob
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
		}
		return &resource, nil
	case "UpdateProfile":
		var resource v1.UpdateProfile
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
		}
		return &resource, nil
	case "UpdateTask":
		var resource v1.UpdateTask
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal UpdateTask: %w", err)
		}
		return &resource, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

func (c *StorageClient) List(ctx context.Context, kind string) ([]interface{}, error) {
	items, err := c.backend.LoadAll(ctx, kind)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "DeviceProfile":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.DeviceProfile
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal DeviceProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "FirmwareProfile":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.FirmwareProfile
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal FirmwareProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "LookupJob":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.LookupJob
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal LookupJob: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "UpdateJob":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.UpdateJob
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal UpdateJob: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "UpdateProfile":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.UpdateProfile
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal UpdateProfile: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "UpdateTask":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.UpdateTask
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal UpdateTask: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

func (c *StorageClient) Update(ctx context.Context, resource interface{}) error {
	data, err := json.Marshal(resource)
	if err != nil {
		return fmt.Errorf("failed to marshal resource: %w", err)
	}

	// Extract kind and UID based on type
	switch res := resource.(type) {
	case *v1.DeviceProfile:
		return c.backend.Save(ctx, "DeviceProfile", res.Metadata.UID, data)
	case *v1.FirmwareProfile:
		return c.backend.Save(ctx, "FirmwareProfile", res.Metadata.UID, data)
	case *v1.LookupJob:
		return c.backend.Save(ctx, "LookupJob", res.Metadata.UID, data)
	case *v1.UpdateJob:
		return c.backend.Save(ctx, "UpdateJob", res.Metadata.UID, data)
	case *v1.UpdateProfile:
		return c.backend.Save(ctx, "UpdateProfile", res.Metadata.UID, data)
	case *v1.UpdateTask:
		return c.backend.Save(ctx, "UpdateTask", res.Metadata.UID, data)
	default:
		return fmt.Errorf("unsupported resource type: %T", resource)
	}
}

func (c *StorageClient) Create(ctx context.Context, resource interface{}) error {
	return c.Update(ctx, resource)
}

func (c *StorageClient) Delete(ctx context.Context, kind, uid string) error {
	return c.backend.Delete(ctx, kind, uid)
}

func marshalTypedList[T any](items []*T) ([]json.RawMessage, error) {
	var out []json.RawMessage
	for _, item := range items {
		data, err := json.Marshal(item)
		if err != nil {
			return nil, err
		}
		out = append(out, json.RawMessage(data))
	}
	return out, nil
}

func marshalResource(resource interface{}) (json.RawMessage, error) {
	data, err := json.Marshal(resource)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

func extractUID(raw json.RawMessage) (string, error) {
	var wrapper struct {
		Metadata struct {
			UID string `json:"uid"`
		} `json:"metadata"`
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		return "", err
	}
	return wrapper.Metadata.UID, nil
}
