// Code generated by Fabrica dev. DO NOT EDIT.
// Template: apiversion/register.gotmpl
// Generated at: 2026-04-20T13:20:44-07:00

package apiversion

import (
	"github.com/openchami/fabrica/pkg/apiversion"
	"github.com/openchami/fabrica/pkg/versioning"
)

// Registry is the global API version registry
var Registry *apiversion.Registry

func init() {
	Registry = apiversion.NewRegistry()
	Registry.RegisterGroup(apiversion.Group{
		Name:           "example.fabrica.dev",
		StorageVersion: "v1",
		Spokes:         []string{"v1"},
	})
	if err := versioning.GlobalVersionRegistry.RegisterVersion("DeviceProfile", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("FirmwareProfile", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("UpdateProfile", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("UpdateJob", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("UpdateTask", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("LookupJob", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
}

// GetRegistry returns the global version registry
func GetRegistry() *apiversion.Registry {
	return Registry
}
