// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the fms API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//  1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//  2. Run 'make generate-client-cmd' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client deviceprofile [list|get|create|update|patch|delete]
//   - client firmwareprofile [list|get|create|update|patch|delete]
//   - client lookupjob [list|get|create|update|patch|delete]
//   - client updatejob [list|get|create|update|patch|delete]
//   - client updateprofile [list|get|create|update|patch|delete]
//   - client updatetask [list|get|create|update|patch|delete]
//
// Global flags (available for all commands):
//
//	--server       Server URL (env: FMS_SERVER)
//	--timeout      Request timeout (env: FMS_TIMEOUT)
//	--output, -o   Output format: table, json, yaml (env: FMS_OUTPUT)
//	--version, -v  API version to request: v1, v2beta1, etc. (env: FMS_VERSION)
//	--config       Config file path (default: ~/.fms-cli.yaml)
//
// Configuration sources (in order of precedence):
//  1. Command-line flags
//  2. Environment variables (FMS_*)
//  3. Config file (~/.fms-cli.yaml)
//  4. Default values
//
// Usage examples:
//
//	# List all deviceprofiles (default version)
//	client deviceprofile list
//
//	# List deviceprofiles with specific version
//	client deviceprofile list --version v2beta1
//
//	# Get DeviceProfile as v1
//	client deviceprofile get <uid> --version v1
//
//	# Create from JSON file with version
//	cat deviceprofile.json | client deviceprofile create --version v2beta1
//
//	# Create from inline JSON
//	client deviceprofile create --spec '{"name":"deviceprofile-01","description":"Example DeviceProfile"}'
//
//	# Use environment variables
//	export FMS_SERVER=https://fms.example.com
//	export FMS_VERSION=v2beta1
//	client deviceprofile list
//
// To add custom commands:
//  1. Add command definition in template after resource commands
//  2. Register it in init() function
//
// To change output formatting:
//  1. Modify printOutput function to add new formats
//  2. Update output flag validation
//
// To add authentication:
//  1. Add auth flags (--token, --username, etc.)
//  2. Modify getClient to configure auth in http.Client
//  3. Add auth headers in client package
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/bmcdonald3/fms/pkg/client"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	cfgFile    string
	serverURL  string
	timeout    time.Duration
	output     string
	apiVersion string
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "fms CLI",
	Long:  `A command-line interface for managing fms resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.fms-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "fms server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))

	// Environment variable support
	viper.SetEnvPrefix("FMS")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(deviceprofileCmd)
	rootCmd.AddCommand(firmwareprofileCmd)
	rootCmd.AddCommand(lookupjobCmd)
	rootCmd.AddCommand(updatejobCmd)
	rootCmd.AddCommand(updateprofileCmd)
	rootCmd.AddCommand(updatetaskCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".fms-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	c, err := client.NewClient(serverURL, nil)
	if err != nil {
		return nil, err
	}

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

// setNestedField sets a field in a nested map using dot notation
// Example: setNestedField(map, "status.health", "OK") sets map["status"]["health"] = "OK"
func setNestedField(target map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := target

	// Navigate to the parent of the target field
	for _, part := range parts[:len(parts)-1] {
		if current[part] == nil {
			current[part] = make(map[string]interface{})
		}
		if nested, ok := current[part].(map[string]interface{}); ok {
			current = nested
		} else {
			// Convert to map if it's not already
			current[part] = make(map[string]interface{})
			current = current[part].(map[string]interface{})
		}
	}

	// Set the final field
	finalField := parts[len(parts)-1]
	if value == nil {
		// For unset operations, we use JSON Merge Patch null semantics
		current[finalField] = nil
	} else if stringValue, ok := value.(string); ok {
		// Try to parse as JSON first, then as string
		var jsonValue interface{}
		if err := json.Unmarshal([]byte(stringValue), &jsonValue); err == nil {
			current[finalField] = jsonValue
		} else {
			current[finalField] = stringValue
		}
	} else {
		current[finalField] = value
	}
}

// DeviceProfile commands
var deviceprofileCmd = &cobra.Command{
	Use:   "deviceprofile",
	Short: "Manage deviceprofiles",
	Long:  `Create, read, update, patch, and delete deviceprofiles.`,
}

var deviceprofileListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all deviceprofiles",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetDeviceProfiles(ctx)
		if err != nil {
			return fmt.Errorf("failed to list deviceprofiles: %w", err)
		}

		return printOutput(items)
	},
}

var deviceprofileGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a DeviceProfile by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetDeviceProfile(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get DeviceProfile: %w", err)
		}

		return printOutput(item)
	},
}

var deviceprofileCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new DeviceProfile",
	Long: `Create a new DeviceProfile.

Examples:
  # Create from stdin
  echo '{"manufacturer": "example-value", "model": "example-value", "redfishPath": "example-value", "managementIp": "192.168.1.1"}' | client deviceprofile create

  # Create with --spec flag
  client deviceprofile create --spec '{"manufacturer": "example-value", "model": "example-value", "redfishPath": "example-value", "managementIp": "192.168.1.1"}'

Spec fields:
  manufacturer (string) [required]
  model (string) [required]
  redfishPath (string) [required]
  managementIp (string) [required]
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateDeviceProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateDeviceProfile(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create DeviceProfile: %w", err)
		}

		return printOutput(item)
	},
}

var deviceprofileUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing DeviceProfile",
	Long: `Update an existing DeviceProfile.

Examples:
  # Update from stdin
  echo '{"manufacturer": "example-value", "model": "example-value", "redfishPath": "example-value", "managementIp": "192.168.1.1"}' | client deviceprofile update <uid>

  # Update with --spec flag
  client deviceprofile update <uid> --spec '{"manufacturer": "example-value", "model": "example-value", "redfishPath": "example-value", "managementIp": "192.168.1.1"}'

Spec fields:
  manufacturer (string) [required]
  model (string) [required]
  redfishPath (string) [required]
  managementIp (string) [required]
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateDeviceProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateDeviceProfile(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update DeviceProfile: %w", err)
		}

		return printOutput(item)
	},
}

var deviceprofilePatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a DeviceProfile",
	Long: `Patch an existing DeviceProfile spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client deviceprofile patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client deviceprofile patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client deviceprofile patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client deviceprofile patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchDeviceProfile(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch DeviceProfile: %w", err)
		}

		return printOutput(item)
	},
}

var deviceprofileDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a DeviceProfile",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteDeviceProfile(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete DeviceProfile: %w", err)
		}

		fmt.Printf("DeviceProfile %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	deviceprofileCmd.AddCommand(deviceprofileListCmd)
	deviceprofileCmd.AddCommand(deviceprofileGetCmd)
	deviceprofileCmd.AddCommand(deviceprofileCreateCmd)
	deviceprofileCmd.AddCommand(deviceprofileUpdateCmd)
	deviceprofileCmd.AddCommand(deviceprofilePatchCmd)
	deviceprofileCmd.AddCommand(deviceprofileDeleteCmd)

	// Add spec flag for create and update commands
	deviceprofileCreateCmd.Flags().String("spec", "", "DeviceProfile specification in JSON format")
	deviceprofileUpdateCmd.Flags().String("spec", "", "DeviceProfile specification in JSON format")

	// Add patch command flags
	deviceprofilePatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	deviceprofilePatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	deviceprofilePatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	deviceprofilePatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	deviceprofilePatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	deviceprofilePatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// FirmwareProfile commands
var firmwareprofileCmd = &cobra.Command{
	Use:   "firmwareprofile",
	Short: "Manage firmwareprofiles",
	Long:  `Create, read, update, patch, and delete firmwareprofiles.`,
}

var firmwareprofileListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all firmwareprofiles",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetFirmwareProfiles(ctx)
		if err != nil {
			return fmt.Errorf("failed to list firmwareprofiles: %w", err)
		}

		return printOutput(items)
	},
}

var firmwareprofileGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a FirmwareProfile by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetFirmwareProfile(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get FirmwareProfile: %w", err)
		}

		return printOutput(item)
	},
}

var firmwareprofileCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new FirmwareProfile",
	Long: `Create a new FirmwareProfile.

Examples:
  # Create from stdin
  echo '{"versionString": "example-value", "versionNumber": "example-value", "targetComponent": "example-value", "preConditions": "example-value", "postConditions": "example-value", "softwareId": "example-value"}' | client firmwareprofile create

  # Create with --spec flag
  client firmwareprofile create --spec '{"versionString": "example-value", "versionNumber": "example-value", "targetComponent": "example-value", "preConditions": "example-value", "postConditions": "example-value", "softwareId": "example-value"}'

Spec fields:
  versionString (string) [required]
  versionNumber (string) [required]
  targetComponent (string) [required]
  preConditions (string)
  postConditions (string)
  softwareId (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateFirmwareProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateFirmwareProfile(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create FirmwareProfile: %w", err)
		}

		return printOutput(item)
	},
}

var firmwareprofileUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing FirmwareProfile",
	Long: `Update an existing FirmwareProfile.

Examples:
  # Update from stdin
  echo '{"versionString": "example-value", "versionNumber": "example-value", "targetComponent": "example-value", "preConditions": "example-value", "postConditions": "example-value", "softwareId": "example-value"}' | client firmwareprofile update <uid>

  # Update with --spec flag
  client firmwareprofile update <uid> --spec '{"versionString": "example-value", "versionNumber": "example-value", "targetComponent": "example-value", "preConditions": "example-value", "postConditions": "example-value", "softwareId": "example-value"}'

Spec fields:
  versionString (string) [required]
  versionNumber (string) [required]
  targetComponent (string) [required]
  preConditions (string)
  postConditions (string)
  softwareId (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateFirmwareProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateFirmwareProfile(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update FirmwareProfile: %w", err)
		}

		return printOutput(item)
	},
}

var firmwareprofilePatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a FirmwareProfile",
	Long: `Patch an existing FirmwareProfile spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client firmwareprofile patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client firmwareprofile patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client firmwareprofile patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client firmwareprofile patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchFirmwareProfile(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch FirmwareProfile: %w", err)
		}

		return printOutput(item)
	},
}

var firmwareprofileDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a FirmwareProfile",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteFirmwareProfile(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete FirmwareProfile: %w", err)
		}

		fmt.Printf("FirmwareProfile %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	firmwareprofileCmd.AddCommand(firmwareprofileListCmd)
	firmwareprofileCmd.AddCommand(firmwareprofileGetCmd)
	firmwareprofileCmd.AddCommand(firmwareprofileCreateCmd)
	firmwareprofileCmd.AddCommand(firmwareprofileUpdateCmd)
	firmwareprofileCmd.AddCommand(firmwareprofilePatchCmd)
	firmwareprofileCmd.AddCommand(firmwareprofileDeleteCmd)

	// Add spec flag for create and update commands
	firmwareprofileCreateCmd.Flags().String("spec", "", "FirmwareProfile specification in JSON format")
	firmwareprofileUpdateCmd.Flags().String("spec", "", "FirmwareProfile specification in JSON format")

	// Add patch command flags
	firmwareprofilePatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	firmwareprofilePatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	firmwareprofilePatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	firmwareprofilePatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	firmwareprofilePatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	firmwareprofilePatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// LookupJob commands
var lookupjobCmd = &cobra.Command{
	Use:   "lookupjob",
	Short: "Manage lookupjobs",
	Long:  `Create, read, update, patch, and delete lookupjobs.`,
}

var lookupjobListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all lookupjobs",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetLookupJobs(ctx)
		if err != nil {
			return fmt.Errorf("failed to list lookupjobs: %w", err)
		}

		return printOutput(items)
	},
}

var lookupjobGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a LookupJob by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetLookupJob(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get LookupJob: %w", err)
		}

		return printOutput(item)
	},
}

var lookupjobCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new LookupJob",
	Long: `Create a new LookupJob.

Examples:
  # Create from stdin
  echo '{"targetNode": "example-value"}' | client lookupjob create

  # Create with --spec flag
  client lookupjob create --spec '{"targetNode": "example-value"}'

Spec fields:
  targetNode (string) [required]
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateLookupJobRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateLookupJob(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create LookupJob: %w", err)
		}

		return printOutput(item)
	},
}

var lookupjobUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing LookupJob",
	Long: `Update an existing LookupJob.

Examples:
  # Update from stdin
  echo '{"targetNode": "example-value"}' | client lookupjob update <uid>

  # Update with --spec flag
  client lookupjob update <uid> --spec '{"targetNode": "example-value"}'

Spec fields:
  targetNode (string) [required]
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateLookupJobRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateLookupJob(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update LookupJob: %w", err)
		}

		return printOutput(item)
	},
}

var lookupjobPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a LookupJob",
	Long: `Patch an existing LookupJob spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client lookupjob patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client lookupjob patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client lookupjob patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client lookupjob patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchLookupJob(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch LookupJob: %w", err)
		}

		return printOutput(item)
	},
}

var lookupjobDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a LookupJob",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteLookupJob(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete LookupJob: %w", err)
		}

		fmt.Printf("LookupJob %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	lookupjobCmd.AddCommand(lookupjobListCmd)
	lookupjobCmd.AddCommand(lookupjobGetCmd)
	lookupjobCmd.AddCommand(lookupjobCreateCmd)
	lookupjobCmd.AddCommand(lookupjobUpdateCmd)
	lookupjobCmd.AddCommand(lookupjobPatchCmd)
	lookupjobCmd.AddCommand(lookupjobDeleteCmd)

	// Add spec flag for create and update commands
	lookupjobCreateCmd.Flags().String("spec", "", "LookupJob specification in JSON format")
	lookupjobUpdateCmd.Flags().String("spec", "", "LookupJob specification in JSON format")

	// Add patch command flags
	lookupjobPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	lookupjobPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	lookupjobPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	lookupjobPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	lookupjobPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	lookupjobPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// UpdateJob commands
var updatejobCmd = &cobra.Command{
	Use:   "updatejob",
	Short: "Manage updatejobs",
	Long:  `Create, read, update, patch, and delete updatejobs.`,
}

var updatejobListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all updatejobs",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetUpdateJobs(ctx)
		if err != nil {
			return fmt.Errorf("failed to list updatejobs: %w", err)
		}

		return printOutput(items)
	},
}

var updatejobGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a UpdateJob by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetUpdateJob(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get UpdateJob: %w", err)
		}

		return printOutput(item)
	},
}

var updatejobCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new UpdateJob",
	Long: `Create a new UpdateJob.

Examples:
  # Create from stdin
  echo '{"targetNodes": ["["item1","item2"]"], "targetComponent": "example-value", "firmwareRef": "example-value", "dryRun": true, "force": true}' | client updatejob create

  # Create with --spec flag
  client updatejob create --spec '{"targetNodes": ["["item1","item2"]"], "targetComponent": "example-value", "firmwareRef": "example-value", "dryRun": true, "force": true}'

Spec fields:
  targetNodes ([]string) [required]
  targetComponent (string)
  firmwareRef (string)
  dryRun (bool)
  force (bool)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateUpdateJobRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateUpdateJob(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create UpdateJob: %w", err)
		}

		return printOutput(item)
	},
}

var updatejobUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing UpdateJob",
	Long: `Update an existing UpdateJob.

Examples:
  # Update from stdin
  echo '{"targetNodes": ["["item1","item2"]"], "targetComponent": "example-value", "firmwareRef": "example-value", "dryRun": true, "force": true}' | client updatejob update <uid>

  # Update with --spec flag
  client updatejob update <uid> --spec '{"targetNodes": ["["item1","item2"]"], "targetComponent": "example-value", "firmwareRef": "example-value", "dryRun": true, "force": true}'

Spec fields:
  targetNodes ([]string) [required]
  targetComponent (string)
  firmwareRef (string)
  dryRun (bool)
  force (bool)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateUpdateJobRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateUpdateJob(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update UpdateJob: %w", err)
		}

		return printOutput(item)
	},
}

var updatejobPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a UpdateJob",
	Long: `Patch an existing UpdateJob spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client updatejob patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client updatejob patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client updatejob patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client updatejob patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchUpdateJob(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch UpdateJob: %w", err)
		}

		return printOutput(item)
	},
}

var updatejobDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a UpdateJob",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteUpdateJob(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete UpdateJob: %w", err)
		}

		fmt.Printf("UpdateJob %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	updatejobCmd.AddCommand(updatejobListCmd)
	updatejobCmd.AddCommand(updatejobGetCmd)
	updatejobCmd.AddCommand(updatejobCreateCmd)
	updatejobCmd.AddCommand(updatejobUpdateCmd)
	updatejobCmd.AddCommand(updatejobPatchCmd)
	updatejobCmd.AddCommand(updatejobDeleteCmd)

	// Add spec flag for create and update commands
	updatejobCreateCmd.Flags().String("spec", "", "UpdateJob specification in JSON format")
	updatejobUpdateCmd.Flags().String("spec", "", "UpdateJob specification in JSON format")

	// Add patch command flags
	updatejobPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	updatejobPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	updatejobPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	updatejobPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	updatejobPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	updatejobPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// UpdateProfile commands
var updateprofileCmd = &cobra.Command{
	Use:   "updateprofile",
	Short: "Manage updateprofiles",
	Long:  `Create, read, update, patch, and delete updateprofiles.`,
}

var updateprofileListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all updateprofiles",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetUpdateProfiles(ctx)
		if err != nil {
			return fmt.Errorf("failed to list updateprofiles: %w", err)
		}

		return printOutput(items)
	},
}

var updateprofileGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a UpdateProfile by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetUpdateProfile(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get UpdateProfile: %w", err)
		}

		return printOutput(item)
	},
}

var updateprofileCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new UpdateProfile",
	Long: `Create a new UpdateProfile.

Examples:
  # Create from stdin
  echo '{"commandType": "example-value", "payloadPath": "example-value", "successCriteria": "example-value"}' | client updateprofile create

  # Create with --spec flag
  client updateprofile create --spec '{"commandType": "example-value", "payloadPath": "example-value", "successCriteria": "example-value"}'

Spec fields:
  commandType (string) [required]
  payloadPath (string)
  successCriteria (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateUpdateProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateUpdateProfile(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create UpdateProfile: %w", err)
		}

		return printOutput(item)
	},
}

var updateprofileUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing UpdateProfile",
	Long: `Update an existing UpdateProfile.

Examples:
  # Update from stdin
  echo '{"commandType": "example-value", "payloadPath": "example-value", "successCriteria": "example-value"}' | client updateprofile update <uid>

  # Update with --spec flag
  client updateprofile update <uid> --spec '{"commandType": "example-value", "payloadPath": "example-value", "successCriteria": "example-value"}'

Spec fields:
  commandType (string) [required]
  payloadPath (string)
  successCriteria (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateUpdateProfileRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateUpdateProfile(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update UpdateProfile: %w", err)
		}

		return printOutput(item)
	},
}

var updateprofilePatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a UpdateProfile",
	Long: `Patch an existing UpdateProfile spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client updateprofile patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client updateprofile patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client updateprofile patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client updateprofile patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchUpdateProfile(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch UpdateProfile: %w", err)
		}

		return printOutput(item)
	},
}

var updateprofileDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a UpdateProfile",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteUpdateProfile(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete UpdateProfile: %w", err)
		}

		fmt.Printf("UpdateProfile %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	updateprofileCmd.AddCommand(updateprofileListCmd)
	updateprofileCmd.AddCommand(updateprofileGetCmd)
	updateprofileCmd.AddCommand(updateprofileCreateCmd)
	updateprofileCmd.AddCommand(updateprofileUpdateCmd)
	updateprofileCmd.AddCommand(updateprofilePatchCmd)
	updateprofileCmd.AddCommand(updateprofileDeleteCmd)

	// Add spec flag for create and update commands
	updateprofileCreateCmd.Flags().String("spec", "", "UpdateProfile specification in JSON format")
	updateprofileUpdateCmd.Flags().String("spec", "", "UpdateProfile specification in JSON format")

	// Add patch command flags
	updateprofilePatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	updateprofilePatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	updateprofilePatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	updateprofilePatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	updateprofilePatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	updateprofilePatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// UpdateTask commands
var updatetaskCmd = &cobra.Command{
	Use:   "updatetask",
	Short: "Manage updatetasks",
	Long:  `Create, read, update, patch, and delete updatetasks.`,
}

var updatetaskListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all updatetasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetUpdateTasks(ctx)
		if err != nil {
			return fmt.Errorf("failed to list updatetasks: %w", err)
		}

		return printOutput(items)
	},
}

var updatetaskGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a UpdateTask by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetUpdateTask(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get UpdateTask: %w", err)
		}

		return printOutput(item)
	},
}

var updatetaskCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new UpdateTask",
	Long: `Create a new UpdateTask.

Examples:
  # Create from stdin
  echo '{"targetNode": "example-value", "targetComponent": "example-value", "firmwareRef": "example-value", "updateJobId": "example-value"}' | client updatetask create

  # Create with --spec flag
  client updatetask create --spec '{"targetNode": "example-value", "targetComponent": "example-value", "firmwareRef": "example-value", "updateJobId": "example-value"}'

Spec fields:
  targetNode (string) [required]
  targetComponent (string)
  firmwareRef (string)
  updateJobId (string) [required]
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateUpdateTaskRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateUpdateTask(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create UpdateTask: %w", err)
		}

		return printOutput(item)
	},
}

var updatetaskUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing UpdateTask",
	Long: `Update an existing UpdateTask.

Examples:
  # Update from stdin
  echo '{"targetNode": "example-value", "targetComponent": "example-value", "firmwareRef": "example-value", "updateJobId": "example-value"}' | client updatetask update <uid>

  # Update with --spec flag
  client updatetask update <uid> --spec '{"targetNode": "example-value", "targetComponent": "example-value", "firmwareRef": "example-value", "updateJobId": "example-value"}'

Spec fields:
  targetNode (string) [required]
  targetComponent (string)
  firmwareRef (string)
  updateJobId (string) [required]
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateUpdateTaskRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateUpdateTask(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update UpdateTask: %w", err)
		}

		return printOutput(item)
	},
}

var updatetaskPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a UpdateTask",
	Long: `Patch an existing UpdateTask spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client updatetask patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client updatetask patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client updatetask patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client updatetask patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchUpdateTask(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch UpdateTask: %w", err)
		}

		return printOutput(item)
	},
}

var updatetaskDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a UpdateTask",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteUpdateTask(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete UpdateTask: %w", err)
		}

		fmt.Printf("UpdateTask %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	updatetaskCmd.AddCommand(updatetaskListCmd)
	updatetaskCmd.AddCommand(updatetaskGetCmd)
	updatetaskCmd.AddCommand(updatetaskCreateCmd)
	updatetaskCmd.AddCommand(updatetaskUpdateCmd)
	updatetaskCmd.AddCommand(updatetaskPatchCmd)
	updatetaskCmd.AddCommand(updatetaskDeleteCmd)

	// Add spec flag for create and update commands
	updatetaskCreateCmd.Flags().String("spec", "", "UpdateTask specification in JSON format")
	updatetaskUpdateCmd.Flags().String("spec", "", "UpdateTask specification in JSON format")

	// Add patch command flags
	updatetaskPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	updatetaskPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	updatetaskPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	updatetaskPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	updatetaskPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	updatetaskPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}
