// Code generated by inventory-codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
// This file registers all reconcilers with the reconciliation controller.
package reconcilers

import (
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/reconcile"
)

// RegisterReconcilers registers all resource reconcilers with the controller.
//
// This is called during server startup to enable automatic reconciliation
// for all registered resource types.
//
// Parameters:
//   - controller: The reconciliation controller
//   - client: Client for accessing resource storage
//   - eventBus: Event bus for publishing events
//
// Returns:
//   - error: If registration fails
//
// Usage:
//
//	controller := reconcile.NewController(eventBus, storage)
//	if err := RegisterReconcilers(controller, client, eventBus); err != nil {
//	    log.Fatal(err)
//	}
//	controller.Start(ctx)
func RegisterReconcilers(controller *reconcile.Controller, client reconcile.ClientInterface, eventBus events.EventBus) error {
	// Register DeviceProfile reconciler
	deviceprofilesReconciler := NewDefaultDeviceProfileReconciler(client, eventBus)
	if err := controller.RegisterReconciler(deviceprofilesReconciler); err != nil {
		return err
	}
	// Register FirmwareManifest reconciler
	firmwaremanifestsReconciler := NewDefaultFirmwareManifestReconciler(client, eventBus)
	if err := controller.RegisterReconciler(firmwaremanifestsReconciler); err != nil {
		return err
	}
	// Register LookupJob reconciler
	lookupjobsReconciler := NewDefaultLookupJobReconciler(client, eventBus)
	if err := controller.RegisterReconciler(lookupjobsReconciler); err != nil {
		return err
	}
	// Register UpdateJob reconciler
	updatejobsReconciler := NewDefaultUpdateJobReconciler(client, eventBus)
	if err := controller.RegisterReconciler(updatejobsReconciler); err != nil {
		return err
	}
	// Register UpdateProfile reconciler
	updateprofilesReconciler := NewDefaultUpdateProfileReconciler(client, eventBus)
	if err := controller.RegisterReconciler(updateprofilesReconciler); err != nil {
		return err
	}

	return nil
}

// GetRegisteredReconcilers returns a list of all registered reconciler names.
//
// This is useful for monitoring and debugging.
func GetRegisteredReconcilers() []string {
	return []string{
		"DeviceProfile",
		"FirmwareManifest",
		"LookupJob",
		"UpdateJob",
		"UpdateProfile",
	}
}
